import React, { useState } from 'react';
import { Input, Button, Label, Icons, CopyBtn } from './_common';

const Result = ({ label, value }) => <div className="p-4 rounded-lg bg-indigo-50 border border-indigo-100"><div className="text-xs text-indigo-700 font-semibold uppercase tracking-wider">{label}</div><div className="text-2xl font-bold text-slate-900 mt-1">{value}</div></div>;

export const AgeCalculatorTool = () => {
  const [d, setD] = useState('');
  let res = null;
  if (d) { const b = new Date(d), n = new Date(); let y = n.getFullYear()-b.getFullYear(), m = n.getMonth()-b.getMonth(), dd = n.getDate()-b.getDate(); if (dd<0){m--; dd+=30;} if (m<0){y--; m+=12;} const days = Math.floor((n-b)/(1000*60*60*24)); res = { y, m, dd, days }; }
  return (<div><Label>Date of birth</Label><Input type="date" value={d} onChange={e=>setD(e.target.value)} className="mt-1.5 max-w-xs" />{res && <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-5"><Result label="Years" value={res.y} /><Result label="Months" value={res.m} /><Result label="Days" value={res.dd} /><Result label="Total days" value={res.days.toLocaleString()} /></div>}</div>);
};

export const PercentageCalculatorTool = () => {
  const [a, setA] = useState(20); const [b, setB] = useState(200);
  const pct = b ? ((a/b)*100).toFixed(2) : 0;
  return (<div className="grid grid-cols-2 gap-3 max-w-md"><div><Label>Value</Label><Input type="number" value={a} onChange={e=>setA(e.target.value)} className="mt-1.5" /></div><div><Label>Of total</Label><Input type="number" value={b} onChange={e=>setB(e.target.value)} className="mt-1.5" /></div><div className="col-span-2"><Result label={`${a} is`} value={`${pct}% of ${b}`} /></div></div>);
};

export const AverageCalculatorTool = () => {
  const [nums, setNums] = useState('10, 20, 30, 40, 50');
  const arr = nums.split(/[\s,]+/).map(Number).filter(n=>!isNaN(n));
  const sum = arr.reduce((a,b)=>a+b,0); const avg = arr.length ? (sum/arr.length) : 0;
  return (<div><Label>Numbers (comma-separated)</Label><Input value={nums} onChange={e=>setNums(e.target.value)} className="mt-1.5" /><div className="grid grid-cols-3 gap-3 mt-4"><Result label="Count" value={arr.length} /><Result label="Sum" value={sum.toLocaleString()} /><Result label="Average" value={avg.toFixed(2)} /></div></div>);
};

export const DiscountCalculatorTool = () => {
  const [p, setP] = useState(100); const [d, setD] = useState(20);
  const final = (p - p*d/100).toFixed(2); const saved = (p*d/100).toFixed(2);
  return (<div className="grid grid-cols-2 gap-3 max-w-md"><div><Label>Original price</Label><Input type="number" value={p} onChange={e=>setP(e.target.value)} className="mt-1.5" /></div><div><Label>Discount %</Label><Input type="number" value={d} onChange={e=>setD(e.target.value)} className="mt-1.5" /></div><div className="col-span-2 grid grid-cols-2 gap-3"><Result label="You save" value={`$${saved}`} /><Result label="Final price" value={`$${final}`} /></div></div>);
};

export const SalesTaxCalculatorTool = () => {
  const [p, setP] = useState(100); const [r, setR] = useState(8);
  const tax = (p*r/100).toFixed(2); const total = (p*(1+r/100)).toFixed(2);
  return (<div className="grid grid-cols-2 gap-3 max-w-md"><div><Label>Net amount</Label><Input type="number" value={p} onChange={e=>setP(e.target.value)} className="mt-1.5" /></div><div><Label>Tax rate %</Label><Input type="number" value={r} onChange={e=>setR(e.target.value)} className="mt-1.5" /></div><div className="col-span-2 grid grid-cols-2 gap-3"><Result label="Tax" value={`$${tax}`} /><Result label="Total" value={`$${total}`} /></div></div>);
};

export const MarginCalculatorTool = () => {
  const [cost, setCost] = useState(50); const [rev, setRev] = useState(100);
  const profit = (rev-cost).toFixed(2); const margin = rev ? ((rev-cost)/rev*100).toFixed(2) : 0;
  return (<div className="grid grid-cols-2 gap-3 max-w-md"><div><Label>Cost</Label><Input type="number" value={cost} onChange={e=>setCost(e.target.value)} className="mt-1.5" /></div><div><Label>Revenue</Label><Input type="number" value={rev} onChange={e=>setRev(e.target.value)} className="mt-1.5" /></div><div className="col-span-2 grid grid-cols-2 gap-3"><Result label="Profit" value={`$${profit}`} /><Result label="Margin %" value={`${margin}%`} /></div></div>);
};

export const LoanCalculatorTool = () => {
  const [P, setP] = useState(10000); const [r, setR] = useState(5); const [yrs, setYrs] = useState(3);
  const n = yrs*12; const rm = r/100/12; const m = rm ? (P*rm*Math.pow(1+rm,n))/(Math.pow(1+rm,n)-1) : P/n;
  return (<div className="grid grid-cols-3 gap-3 max-w-2xl"><div><Label>Loan amount</Label><Input type="number" value={P} onChange={e=>setP(e.target.value)} className="mt-1.5" /></div><div><Label>Annual rate %</Label><Input type="number" value={r} onChange={e=>setR(e.target.value)} className="mt-1.5" /></div><div><Label>Years</Label><Input type="number" value={yrs} onChange={e=>setYrs(e.target.value)} className="mt-1.5" /></div><div className="col-span-3 grid grid-cols-3 gap-3"><Result label="Monthly" value={`$${m.toFixed(2)}`} /><Result label="Total paid" value={`$${(m*n).toFixed(2)}`} /><Result label="Interest" value={`$${(m*n-P).toFixed(2)}`} /></div></div>);
};

export const GSTCalculatorTool = () => { const [p, setP] = useState(100); const [r, setR] = useState(18); const gst = (p*r/100).toFixed(2); const tot = (p*(1+r/100)).toFixed(2); return (<div className="grid grid-cols-2 gap-3 max-w-md"><div><Label>Amount</Label><Input type="number" value={p} onChange={e=>setP(e.target.value)} className="mt-1.5" /></div><div><Label>GST %</Label><Input type="number" value={r} onChange={e=>setR(e.target.value)} className="mt-1.5" /></div><div className="col-span-2 grid grid-cols-2 gap-3"><Result label="GST" value={`$${gst}`} /><Result label="Total" value={`$${tot}`} /></div></div>); };
export const PayPalFeeTool = () => { const [a, setA] = useState(100); const fee = (a*0.0349 + 0.49).toFixed(2); const net = (a-fee).toFixed(2); return (<div className="max-w-md"><Label>Amount received</Label><Input type="number" value={a} onChange={e=>setA(e.target.value)} className="mt-1.5" /><div className="grid grid-cols-2 gap-3 mt-4"><Result label="PayPal fee" value={`$${fee}`} /><Result label="You get" value={`$${net}`} /></div></div>); };
export const StripeFeeTool = () => { const [a, setA] = useState(100); const fee = (a*0.029 + 0.30).toFixed(2); const net = (a-fee).toFixed(2); return (<div className="max-w-md"><Label>Amount</Label><Input type="number" value={a} onChange={e=>setA(e.target.value)} className="mt-1.5" /><div className="grid grid-cols-2 gap-3 mt-4"><Result label="Stripe fee" value={`$${fee}`} /><Result label="You get" value={`$${net}`} /></div></div>); };
export const CPMCalculatorTool = () => { const [cost, setCost] = useState(500); const [imp, setImp] = useState(100000); const cpm = imp ? (cost/imp*1000).toFixed(2) : 0; return (<div className="grid grid-cols-2 gap-3 max-w-md"><div><Label>Total cost</Label><Input type="number" value={cost} onChange={e=>setCost(e.target.value)} className="mt-1.5" /></div><div><Label>Impressions</Label><Input type="number" value={imp} onChange={e=>setImp(e.target.value)} className="mt-1.5" /></div><div className="col-span-2"><Result label="CPM" value={`$${cpm}`} /></div></div>); };
export const DaysCalculatorTool = () => { const [a, setA] = useState(''); const [b, setB] = useState(''); const days = (a&&b) ? Math.abs(Math.round((new Date(b)-new Date(a))/(86400000))) : 0; return (<div className="grid grid-cols-2 gap-3 max-w-md"><div><Label>From</Label><Input type="date" value={a} onChange={e=>setA(e.target.value)} className="mt-1.5" /></div><div><Label>To</Label><Input type="date" value={b} onChange={e=>setB(e.target.value)} className="mt-1.5" /></div><div className="col-span-2"><Result label="Days between" value={days.toLocaleString()} /></div></div>); };
export const HoursCalculatorTool = () => { const [a, setA] = useState('09:00'); const [b, setB] = useState('17:30'); const diff = (() => { const [h1,m1]=a.split(':').map(Number); const [h2,m2]=b.split(':').map(Number); const m = (h2*60+m2)-(h1*60+m1); return m>=0?`${Math.floor(m/60)}h ${m%60}m`:'—'; })(); return (<div className="grid grid-cols-2 gap-3 max-w-md"><div><Label>Start</Label><Input type="time" value={a} onChange={e=>setA(e.target.value)} className="mt-1.5" /></div><div><Label>End</Label><Input type="time" value={b} onChange={e=>setB(e.target.value)} className="mt-1.5" /></div><div className="col-span-2"><Result label="Duration" value={diff} /></div></div>); };
export const MonthCalculatorTool = () => { const [a, setA] = useState(''); const [b, setB] = useState(''); const months = (a&&b) ? Math.abs((new Date(b).getFullYear()-new Date(a).getFullYear())*12 + (new Date(b).getMonth()-new Date(a).getMonth())) : 0; return (<div className="grid grid-cols-2 gap-3 max-w-md"><div><Label>From</Label><Input type="date" value={a} onChange={e=>setA(e.target.value)} className="mt-1.5" /></div><div><Label>To</Label><Input type="date" value={b} onChange={e=>setB(e.target.value)} className="mt-1.5" /></div><div className="col-span-2"><Result label="Months between" value={months} /></div></div>); };
export const ConfidenceIntervalTool = () => { const [mean, setMean] = useState(50); const [sd, setSd] = useState(10); const [n, setN] = useState(30); const [c, setC] = useState(95); const z = c===90?1.645:c===99?2.576:1.96; const margin = z*sd/Math.sqrt(n); return (<div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><div><Label>Mean</Label><Input type="number" value={mean} onChange={e=>setMean(parseFloat(e.target.value))} className="mt-1.5" /></div><div><Label>SD</Label><Input type="number" value={sd} onChange={e=>setSd(parseFloat(e.target.value))} className="mt-1.5" /></div><div><Label>Sample n</Label><Input type="number" value={n} onChange={e=>setN(parseInt(e.target.value))} className="mt-1.5" /></div><div><Label>Confidence %</Label><Input type="number" value={c} onChange={e=>setC(parseInt(e.target.value))} className="mt-1.5" /></div><div className="col-span-full"><Result label={`${c}% CI`} value={`${(mean-margin).toFixed(2)} — ${(mean+margin).toFixed(2)}`} /></div></div>); };
export const ProbabilityTool = () => { const [f, setF] = useState(1); const [t, setT] = useState(6); const p = t ? (f/t*100).toFixed(2) : 0; return (<div className="grid grid-cols-2 gap-3 max-w-md"><div><Label>Favorable</Label><Input type="number" value={f} onChange={e=>setF(e.target.value)} className="mt-1.5" /></div><div><Label>Total outcomes</Label><Input type="number" value={t} onChange={e=>setT(e.target.value)} className="mt-1.5" /></div><div className="col-span-2"><Result label="Probability" value={`${p}%`} /></div></div>); };
export const CalorieCalculatorTool = () => { const [w, setW] = useState(70); const [h, setH] = useState(170); const [a, setA] = useState(30); const [g, setG] = useState('male'); const bmr = g==='male' ? 10*w+6.25*h-5*a+5 : 10*w+6.25*h-5*a-161; return (<div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><div><Label>Weight (kg)</Label><Input type="number" value={w} onChange={e=>setW(parseFloat(e.target.value))} className="mt-1.5" /></div><div><Label>Height (cm)</Label><Input type="number" value={h} onChange={e=>setH(parseFloat(e.target.value))} className="mt-1.5" /></div><div><Label>Age</Label><Input type="number" value={a} onChange={e=>setA(parseInt(e.target.value))} className="mt-1.5" /></div><div><Label>Gender</Label><select value={g} onChange={e=>setG(e.target.value)} className="mt-1.5 h-10 w-full border border-slate-200 rounded-md px-3 text-sm"><option value="male">Male</option><option value="female">Female</option></select></div><div className="col-span-full"><Result label="BMR (calories/day)" value={bmr.toFixed(0)} /></div></div>); };
export const TDEECalculatorTool = () => { const [w, setW] = useState(70); const [h, setH] = useState(170); const [a, setA] = useState(30); const [g, setG] = useState('male'); const [act, setAct] = useState(1.55); const bmr = g==='male' ? 10*w+6.25*h-5*a+5 : 10*w+6.25*h-5*a-161; const tdee = bmr*act; return (<div className="grid grid-cols-2 lg:grid-cols-5 gap-3"><div><Label>Weight</Label><Input type="number" value={w} onChange={e=>setW(parseFloat(e.target.value))} className="mt-1.5" /></div><div><Label>Height</Label><Input type="number" value={h} onChange={e=>setH(parseFloat(e.target.value))} className="mt-1.5" /></div><div><Label>Age</Label><Input type="number" value={a} onChange={e=>setA(parseInt(e.target.value))} className="mt-1.5" /></div><div><Label>Gender</Label><select value={g} onChange={e=>setG(e.target.value)} className="mt-1.5 h-10 w-full border border-slate-200 rounded-md px-3 text-sm"><option value="male">Male</option><option value="female">Female</option></select></div><div><Label>Activity</Label><select value={act} onChange={e=>setAct(parseFloat(e.target.value))} className="mt-1.5 h-10 w-full border border-slate-200 rounded-md px-3 text-sm"><option value="1.2">Sedentary</option><option value="1.375">Light</option><option value="1.55">Moderate</option><option value="1.725">Active</option><option value="1.9">Very active</option></select></div><div className="col-span-full"><Result label="TDEE (calories/day)" value={tdee.toFixed(0)} /></div></div>); };
export const AdsenseCalculatorTool = () => { const [pv, setPv] = useState(100000); const [ctr, setCtr] = useState(2); const [cpc, setCpc] = useState(0.3); const earn = (pv*ctr/100*cpc).toFixed(2); return (<div className="grid grid-cols-3 gap-3 max-w-2xl"><div><Label>Pageviews/day</Label><Input type="number" value={pv} onChange={e=>setPv(e.target.value)} className="mt-1.5" /></div><div><Label>CTR %</Label><Input type="number" step="0.1" value={ctr} onChange={e=>setCtr(e.target.value)} className="mt-1.5" /></div><div><Label>CPC $</Label><Input type="number" step="0.01" value={cpc} onChange={e=>setCpc(e.target.value)} className="mt-1.5" /></div><div className="col-span-3 grid grid-cols-3 gap-3"><Result label="Daily" value={`$${earn}`} /><Result label="Monthly" value={`$${(earn*30).toFixed(2)}`} /><Result label="Yearly" value={`$${(earn*365).toFixed(2)}`} /></div></div>); };
