// Master registry of all Protooly tools with SEO-friendly descriptions and keywords.
// Each tool: { id, name, slug, icon, description, keywords, functional, category }

export const CATEGORIES = [
  { id: 'pdf', name: 'PDF Tools', icon: 'FileText', color: 'rose', desc: 'Convert, edit, merge, split & sign PDF files online.' },
  { id: 'ai', name: 'AI Writing Tools', icon: 'Sparkles', color: 'violet', desc: 'AI-powered writing, detection & rewriting tools.' },
  { id: 'youtube', name: 'YouTube Tools', icon: 'Youtube', color: 'red', desc: 'Tags, titles, thumbnails, statistics & analytics.' },
  { id: 'text', name: 'Text Tools', icon: 'Type', color: 'amber', desc: 'Manipulate, format and analyze text.' },
  { id: 'seo', name: 'SEO Tools', icon: 'TrendingUp', color: 'emerald', desc: 'Audit, analyze and optimize for search engines.' },
  { id: 'web', name: 'Domain & Web Tools', icon: 'Globe', color: 'sky', desc: 'Domain, IP, DNS, hosting & browser utilities.' },
  { id: 'code', name: 'Code Tools', icon: 'Code2', color: 'indigo', desc: 'Beautify, minify and convert HTML/CSS/JS code.' },
  { id: 'json', name: 'JSON & Data', icon: 'Braces', color: 'cyan', desc: 'JSON, XML, CSV and TSV converters.' },
  { id: 'image', name: 'Image Tools', icon: 'Image', color: 'fuchsia', desc: 'Convert, resize, crop and edit images.' },
  { id: 'calc', name: 'Calculators', icon: 'Calculator', color: 'orange', desc: 'Financial, health & math calculators.' },
  { id: 'units', name: 'Unit Converters', icon: 'ArrowRightLeft', color: 'teal', desc: 'Convert between units of measurement.' },
  { id: 'numbers', name: 'Number Systems', icon: 'Binary', color: 'slate', desc: 'Binary, HEX, ASCII, Octal & Decimal converters.' },
  { id: 'misc', name: 'Other Utilities', icon: 'Wrench', color: 'stone', desc: 'QR codes, password generator and more.' }
];

const t = (id, name, category, icon, description, keywords) => ({
  id,
  name,
  slug: name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
  category,
  icon,
  description,
  keywords,
  functional: true, // assume true; registry will fall back to ComingSoon if no impl
});

export const TOOLS = [
  // PDF Tools (1-28)
  t(1, 'Merge PDF', 'pdf', 'FilePlus2', 'Combine multiple PDF files into a single document online \u2014 free, fast, and secure. Merge PDFs in your browser with no uploads to any server.', ['merge pdf','combine pdf','join pdf','pdf merger']),
  t(2, 'Split PDF', 'pdf', 'Scissors', 'Split a PDF into separate pages or page ranges instantly. Extract specific pages from any PDF document for free.', ['split pdf','separate pdf','extract pdf pages','pdf splitter']),
  t(3, 'Compress PDF', 'pdf', 'Archive', 'Reduce PDF file size while preserving quality. Compress PDFs to share via email or upload faster without losing readability.', ['compress pdf','reduce pdf size','pdf optimizer','shrink pdf']),
  t(4, 'PDF to Word', 'pdf', 'FileType', 'Convert PDF documents to editable Word (.docx) files online. Preserve layout, fonts and formatting for free.', ['pdf to word','pdf to docx','convert pdf','pdf converter']),
  t(5, 'PDF to PowerPoint', 'pdf', 'Presentation', 'Convert PDF files to editable PowerPoint (.pptx) presentations. Turn reports into slides in seconds.', ['pdf to powerpoint','pdf to pptx','pdf to ppt','presentation converter']),
  t(6, 'PDF to Excel', 'pdf', 'Sheet', 'Extract tables from PDF into Excel (.xlsx) spreadsheets. Convert data-rich PDFs to editable Excel files.', ['pdf to excel','pdf to xlsx','extract pdf tables','pdf to spreadsheet']),
  t(7, 'Word to PDF', 'pdf', 'FileType', 'Convert Word (.docx) documents to PDF format quickly. Preserve all formatting, images and styles.', ['word to pdf','docx to pdf','doc to pdf','word converter']),
  t(8, 'PowerPoint to PDF', 'pdf', 'Presentation', 'Convert PowerPoint (.pptx) presentations to PDF documents for easier sharing and printing.', ['powerpoint to pdf','pptx to pdf','ppt to pdf','presentation to pdf']),
  t(9, 'Excel to PDF', 'pdf', 'Sheet', 'Convert Excel (.xlsx) spreadsheets to PDF documents. Lock layouts and share data securely.', ['excel to pdf','xlsx to pdf','spreadsheet to pdf','xls to pdf']),
  t(10, 'Edit PDF', 'pdf', 'Pencil', 'Edit PDF files online \u2014 add text, images, shapes or annotations. Modify any PDF for free without installing software.', ['edit pdf','pdf editor','annotate pdf','modify pdf']),
  t(11, 'PDF to JPG', 'pdf', 'Image', 'Convert each page of a PDF to high-quality JPG images. Export PDF pages as JPEG photos for embedding or sharing.', ['pdf to jpg','pdf to jpeg','pdf to image','extract pdf images']),
  t(12, 'JPG to PDF', 'pdf', 'FileImage', 'Convert JPG or JPEG images into a single PDF document. Merge multiple photos into one professional PDF.', ['jpg to pdf','jpeg to pdf','image to pdf','photo to pdf']),
  t(13, 'Sign PDF', 'pdf', 'PenLine', 'Add electronic signatures to PDF documents online. Sign contracts and agreements securely with drawn or typed signatures.', ['sign pdf','esign pdf','electronic signature','pdf signature']),
  t(14, 'Watermark PDF', 'pdf', 'Droplets', 'Add text or image watermarks to PDF documents. Protect your PDFs with custom branding or copyright stamps.', ['watermark pdf','add watermark','pdf watermark','brand pdf']),
  t(15, 'Rotate PDF', 'pdf', 'RotateCw', 'Rotate PDF pages by 90, 180 or 270 degrees. Fix sideways or upside-down PDF pages instantly.', ['rotate pdf','turn pdf','pdf rotation','fix pdf orientation']),
  t(16, 'HTML to PDF', 'pdf', 'Code', 'Convert HTML pages or web URLs to PDF documents. Save web pages as PDF with preserved styles.', ['html to pdf','website to pdf','url to pdf','webpage to pdf']),
  t(17, 'Unlock PDF', 'pdf', 'Unlock', 'Remove password protection from PDF documents you own. Unlock secured PDFs to enable copying and printing.', ['unlock pdf','remove pdf password','decrypt pdf','pdf unlocker']),
  t(18, 'Protect PDF', 'pdf', 'Lock', 'Add password protection to PDF files. Encrypt PDFs to prevent unauthorized access, copying or printing.', ['protect pdf','password pdf','encrypt pdf','secure pdf']),
  t(19, 'Organize PDF', 'pdf', 'Layers', 'Reorder, delete or rearrange PDF pages with drag and drop. Restructure any PDF document visually.', ['organize pdf','reorder pdf','rearrange pdf pages','pdf page manager']),
  t(20, 'PDF to PDF/A', 'pdf', 'FileCheck', 'Convert standard PDFs to PDF/A format for long-term archiving and ISO-compliant storage.', ['pdf to pdfa','archive pdf','pdfa converter','iso pdf']),
  t(21, 'Repair PDF', 'pdf', 'Wrench', 'Fix corrupted or damaged PDF files. Recover content from broken PDFs that won\u2019t open.', ['repair pdf','fix pdf','recover pdf','damaged pdf']),
  t(22, 'PDF Page Numbers', 'pdf', 'Hash', 'Add page numbers to PDF documents with custom positions, fonts and styles.', ['pdf page numbers','number pdf pages','add pagination','pdf footer']),
  t(23, 'Scan to PDF', 'pdf', 'ScanLine', 'Scan documents from your camera and save as a PDF. Turn paper documents into shareable PDFs.', ['scan to pdf','camera to pdf','document scanner','pdf scanner']),
  t(24, 'OCR PDF', 'pdf', 'ScanText', 'Extract text from scanned PDF images using OCR. Make image-based PDFs searchable and selectable.', ['ocr pdf','pdf ocr','scanned pdf','text recognition']),
  t(25, 'Compare PDF', 'pdf', 'GitCompare', 'Compare two PDF documents side-by-side and highlight differences in text and layout.', ['compare pdf','pdf diff','pdf comparison','side by side pdf']),
  t(26, 'Redact PDF', 'pdf', 'EyeOff', 'Permanently remove sensitive content from PDFs. Redact confidential text, names or numbers securely.', ['redact pdf','remove pdf content','censor pdf','hide pdf text']),
  t(27, 'Crop PDF', 'pdf', 'Crop', 'Crop PDF pages to remove margins or focus on specific content areas.', ['crop pdf','trim pdf','cut pdf pages','pdf crop']),
  t(28, 'PDF Forms', 'pdf', 'FormInput', 'Fill out interactive PDF forms or create new fillable PDF forms with text fields, checkboxes and signatures.', ['pdf forms','fillable pdf','interactive pdf','pdf form filler']),
  // AI Writing Tools (29-38, 61)
  t(29, 'AI Summarizer', 'ai', 'Sparkles', 'Summarize long articles, essays or PDFs into key bullet points using advanced AI. Get the gist of any text instantly.', ['ai summarizer','summarize text','article summary','ai summary']),
  t(30, 'Paraphrasing Tool', 'ai', 'Replace', 'Rewrite sentences or paragraphs to improve clarity while preserving meaning. AI-powered paraphraser for students and writers.', ['paraphrase','rewrite text','ai paraphraser','sentence rewriter']),
  t(31, 'Translate Text', 'ai', 'Languages', 'Translate text or full documents into 100+ languages using AI. High-accuracy translation for any content.', ['translate text','ai translator','translation tool','document translator']),
  t(32, 'AI Detector', 'ai', 'ShieldCheck', 'Detect whether a text was written by AI (ChatGPT, Claude, Gemini) or by a human with confidence scores.', ['ai detector','chatgpt detector','ai content checker','ai writing detection']),
  t(33, 'AI Text Generator', 'ai', 'Bot', 'Generate high-quality text on any topic using AI. Create blog posts, emails, product descriptions and more.', ['ai text generator','content generator','ai writer','text creation']),
  t(34, 'Reverse Image Search', 'ai', 'SearchCheck', 'Search the web using an image to find sources, similar pictures or higher resolution versions.', ['reverse image search','find image source','image lookup','search by image']),
  t(35, 'Plagiarism Checker', 'ai', 'CopyCheck', 'Scan text against billions of web pages and academic sources to detect duplicate or copied content.', ['plagiarism checker','duplicate content','plagiarism detector','copyscape']),
  t(36, 'AI Grammar Checker', 'ai', 'SpellCheck', 'Find and fix grammar, spelling, punctuation and style mistakes in your writing with AI suggestions.', ['grammar checker','spell checker','ai proofreader','writing assistant']),
  t(37, 'AI Humanizer', 'ai', 'UserCheck', 'Rewrite AI-generated text to sound natural and human, bypassing AI detection while preserving meaning.', ['ai humanizer','humanize ai text','undetectable ai','bypass ai detection']),
  t(38, 'Citation Generator', 'ai', 'Quote', 'Generate accurate citations in APA, MLA, Chicago and Harvard styles for books, articles, websites and more.', ['citation generator','apa citation','mla citation','bibliography generator']),
  t(61, 'Article Rewriter', 'ai', 'PenTool', 'Spin and rewrite articles to create unique versions while keeping the original meaning. Great for content marketers.', ['article rewriter','content spinner','article spinner','rewrite article']),
  // YouTube Tools (42-60)
  t(42, 'YouTube Trends Checker', 'youtube', 'TrendingUp', 'Discover trending topics, videos and keywords on YouTube to optimize your content strategy.', ['youtube trends','trending videos','youtube analytics','viral videos']),
  t(43, 'YouTube Tag Extractor', 'youtube', 'Tags', 'Extract all tags from any public YouTube video to analyze SEO strategies of competitors.', ['youtube tag extractor','extract youtube tags','video tags','youtube seo']),
  t(44, 'YouTube Tag Generator', 'youtube', 'Tags', 'Generate optimized YouTube video tags based on your topic or keyword for better discoverability.', ['youtube tag generator','video tags','youtube seo tags','tag suggestions']),
  t(45, 'YouTube Hashtag Extractor', 'youtube', 'Hash', 'Extract hashtags from YouTube video titles and descriptions to understand trending hashtag strategies.', ['youtube hashtags','extract hashtags','video hashtags','youtube tags']),
  t(46, 'YouTube Hashtag Generator', 'youtube', 'Hash', 'Generate relevant YouTube hashtags from a keyword to grow your channel\u2019s reach and engagement.', ['youtube hashtag generator','hashtag ideas','youtube growth','viral hashtags']),
  t(47, 'YouTube Title Extractor', 'youtube', 'Type', 'Extract titles from any YouTube video URL for content research and SEO analysis.', ['youtube title','extract title','video title','youtube research']),
  t(48, 'YouTube Title Generator', 'youtube', 'Type', 'Generate catchy YouTube video titles that boost CTR using AI suggestions and proven formulas.', ['youtube title generator','click bait titles','video title ideas','youtube ctr']),
  t(49, 'YouTube Description Extractor', 'youtube', 'AlignLeft', 'Extract full descriptions from YouTube videos to study top creators\u2019 strategies.', ['youtube description','extract description','video description','youtube research']),
  t(50, 'YouTube Description Generator', 'youtube', 'AlignLeft', 'Generate SEO-optimized YouTube video descriptions with hashtags, links and call-to-actions.', ['youtube description generator','video description','youtube seo','description template']),
  t(51, 'YouTube Embed Code Generator', 'youtube', 'Code2', 'Generate responsive YouTube embed iframe code with customizable size, autoplay and start time.', ['youtube embed','embed code','iframe generator','youtube iframe']),
  t(52, 'YouTube Channel ID Finder', 'youtube', 'Search', 'Find the unique Channel ID of any YouTube channel from its username, handle or URL.', ['channel id','youtube channel id','find channel id','channel lookup']),
  t(53, 'YouTube Video Statistics', 'youtube', 'BarChart3', 'View detailed statistics for any public YouTube video: views, likes, comments, upload date and tags.', ['youtube video stats','video statistics','youtube analytics','video metrics']),
  t(54, 'YouTube Channel Statistics', 'youtube', 'BarChart3', 'Check subscriber count, total views, video count and growth metrics of any YouTube channel.', ['youtube channel stats','subscriber count','channel analytics','youtube metrics']),
  t(55, 'YouTube Money Calculator', 'youtube', 'DollarSign', 'Estimate YouTube earnings from views, CTR and CPM. Calculate monthly and yearly ad revenue.', ['youtube money calculator','youtube earnings','adsense calculator','youtube income']),
  t(56, 'YouTube Region Restriction Checker', 'youtube', 'Globe', 'Check which countries can watch a specific YouTube video to identify region-blocked content.', ['youtube region','region restriction','blocked countries','geo blocking']),
  t(57, 'YouTube Channel Logo Downloader', 'youtube', 'Image', 'Download the profile picture or logo of any YouTube channel in high resolution.', ['youtube logo downloader','channel logo','profile picture','youtube avatar']),
  t(58, 'YouTube Channel Banner Downloader', 'youtube', 'Image', 'Download the channel art or banner image of any YouTube channel in original quality.', ['youtube banner','channel art','banner downloader','youtube header']),
  t(59, 'YouTube Channel Finder', 'youtube', 'Search', 'Find any YouTube channel by name, niche or keyword. Discover creators in your space.', ['youtube channel finder','find channel','channel search','youtube discovery']),
  t(60, 'YouTube Thumbnail Downloader', 'youtube', 'Image', 'Download YouTube video thumbnails in HD, MQ and SD resolutions. Save any thumbnail as JPG.', ['youtube thumbnail','thumbnail downloader','video thumbnail','hd thumbnail']),
  // SEO Tools (62-63, 79-98)
  t(62, 'Backlink Checker', 'seo', 'Link', 'Analyze the backlink profile of any domain. Find referring domains, anchor texts and link quality.', ['backlink checker','backlink analyzer','seo backlinks','link audit']),
  t(63, 'URL Rewriting Tool', 'seo', 'Link2', 'Rewrite URLs to be SEO-friendly, clean and human-readable. Convert dynamic URLs to static.', ['url rewriting','seo url','clean url','rewrite url']),
  t(79, 'Keyword Density Checker', 'seo', 'Hash', 'Analyze keyword frequency and density in your content. Optimize for SEO without over-stuffing.', ['keyword density','seo analysis','content optimization','keyword analyzer']),
  t(80, 'SEO Site Audit', 'seo', 'ClipboardCheck', 'Run a complete SEO audit of any website. Check meta tags, headings, images, links and performance.', ['seo audit','site audit','seo checker','website analysis']),
  t(81, 'Google Index Checker', 'seo', 'Search', 'Check if your pages are indexed by Google. Find non-indexed URLs that need attention.', ['google index','index checker','indexed pages','search engine index']),
  t(82, 'Google Cache Checker', 'seo', 'Database', 'Check the Google cache status and last cached date of any web page.', ['google cache','cached page','cache checker','google snapshot']),
  t(83, 'Robots.txt Generator', 'seo', 'FileCode', 'Generate a custom robots.txt file to control how search engines crawl your website.', ['robots txt','robots.txt generator','crawler rules','sitemap reference']),
  t(84, 'HTTP Status Code Checker', 'seo', 'Activity', 'Check HTTP status codes (200, 301, 404, 500) of any URL with redirect tracking.', ['http status','status code checker','404 checker','http response']),
  t(85, 'Domain Authority Checker', 'seo', 'Trophy', 'Check the Domain Authority (DA) score of any website to gauge its SEO strength.', ['domain authority','da checker','moz da','seo authority']),
  t(86, 'Page Authority Checker', 'seo', 'Trophy', 'Check the Page Authority (PA) score of any URL to measure individual page SEO power.', ['page authority','pa checker','moz pa','page seo']),
  t(87, 'DA PA Checker', 'seo', 'Trophy', 'Check both Domain Authority and Page Authority scores side by side in one click.', ['da pa checker','domain authority','page authority','seo metrics']),
  t(88, 'Htaccess Redirect Generator', 'seo', 'FileCode', 'Generate .htaccess 301/302 redirect rules for Apache servers to manage URL redirections.', ['htaccess generator','301 redirect','htaccess redirect','apache redirect']),
  t(89, 'Meta Tag Generator', 'seo', 'Tag', 'Generate SEO meta tags including title, description, Open Graph and Twitter cards.', ['meta tag generator','seo meta tags','og tags','twitter card']),
  t(90, 'Meta Tags Analyzer', 'seo', 'Tag', 'Analyze and validate the meta tags of any web page to spot SEO issues quickly.', ['meta tag analyzer','seo analyzer','meta checker','meta validator']),
  t(91, 'Moz Rank Checker', 'seo', 'BarChart3', 'Check the MozRank score of any URL to measure link popularity and authority.', ['moz rank','mozrank checker','link authority','moz seo']),
  t(92, 'Open Graph Checker', 'seo', 'Share2', 'Preview and validate Open Graph meta tags to optimize how links appear on social media.', ['open graph','og tags','social preview','facebook preview']),
  t(93, 'Open Graph Generator', 'seo', 'Share2', 'Generate Open Graph tags for perfect social media previews on Facebook, LinkedIn and Twitter.', ['og generator','open graph generator','social meta tags','og:image']),
  t(94, 'Get HTTP Headers', 'seo', 'List', 'Inspect HTTP response headers of any URL: cache, security, content-type and more.', ['http headers','response headers','header checker','http inspection']),
  t(95, 'Page Size Checker', 'seo', 'Maximize', 'Check the total file size of any web page to optimize loading performance.', ['page size','website size','page weight','page speed']),
  t(96, 'Keywords Suggestion Tool', 'seo', 'Lightbulb', 'Generate keyword ideas and long-tail variations from a seed keyword for SEO research.', ['keyword suggestion','keyword ideas','long tail keywords','keyword research']),
  t(97, 'Redirect Checker', 'seo', 'CornerDownRight', 'Follow and display the full redirect chain of any URL with status codes for each hop.', ['redirect checker','redirect chain','301 checker','url redirect']),
  t(98, 'FAQ Schema Generator', 'seo', 'HelpCircle', 'Generate JSON-LD FAQ schema markup to win rich snippets in Google search results.', ['faq schema','schema generator','json-ld','rich snippets']),
  // Advanced backlink SEO tools (241-249)
  t(241, 'Referring Domains Checker', 'seo', 'Link2', 'Find all referring domains pointing to any website. Analyze unique domain count, authority and link diversity for SEO insights.', ['referring domains','linking domains','seo domains','backlink domains']),
  t(242, 'Broken Backlink Checker', 'seo', 'Unlink', 'Identify broken backlinks (404 links) pointing to your site. Reclaim lost link equity by fixing or redirecting dead links.', ['broken backlinks','404 backlinks','dead links','broken link checker']),
  t(243, 'Lost Backlinks Checker', 'seo', 'TrendingDown', 'Track recently lost backlinks to your domain. Monitor link drops and recover valuable SEO authority before rankings suffer.', ['lost backlinks','removed backlinks','dropped links','backlink monitor']),
  t(244, 'New Backlinks Checker', 'seo', 'TrendingUp', 'Discover newly acquired backlinks to any domain. Monitor fresh link-building wins and competitor link growth in real time.', ['new backlinks','fresh backlinks','recent backlinks','backlink tracker']),
  t(245, 'Anchor Text Checker', 'seo', 'Text', 'Analyze anchor text distribution of backlinks pointing to any URL. Detect over-optimization and improve link diversity for safer SEO.', ['anchor text','anchor analysis','seo anchors','link anchors']),
  t(246, 'Competitor Backlink Checker', 'seo', 'Swords', 'Spy on competitor backlink profiles. Discover their best linking domains and uncover replicable link-building opportunities.', ['competitor backlinks','spy backlinks','competitor analysis','backlink research']),
  t(247, 'Backlink Gap Tool', 'seo', 'GitCompareArrows', 'Compare backlink profiles between your site and competitors. Find domains linking to rivals but not to you for prospecting.', ['backlink gap','link gap','competitor gap','link opportunities']),
  t(248, 'Link Building Opportunity Finder', 'seo', 'Lightbulb', 'Discover high-quality link prospects in your niche. Find resource pages, guest post chances and broken link reclamation targets.', ['link building','link prospects','outreach opportunities','seo link building']),
  t(249, 'Toxic Backlink Checker', 'seo', 'ShieldAlert', 'Detect toxic and spammy backlinks harming your domain. Audit risky links and prepare disavow files to protect rankings.', ['toxic backlinks','spammy links','disavow file','link audit']),
  // Text Tools (64-78, 197-198, 201-202)
  t(64, 'Backwards Text Generator', 'text', 'FlipHorizontal', 'Reverse any text instantly. Convert text to backwards, upside-down or mirror text for fun and social media.', ['reverse text','backwards text','flip text','mirror text']),
  t(65, 'Text to Hashtags', 'text', 'Hash', 'Convert any text or list of words into trending-style hashtags for Instagram, Twitter and TikTok.', ['text to hashtags','hashtag generator','create hashtags','social hashtags']),
  t(66, 'Text Compare Online', 'text', 'GitCompare', 'Compare two pieces of text side-by-side and highlight differences word by word.', ['text compare','diff checker','compare text','text differences']),
  t(67, 'Text to Slug', 'text', 'Link', 'Convert any title or sentence into a clean URL slug. SEO-friendly slug generator for blog posts.', ['text to slug','url slug','slug generator','seo slug']),
  t(68, 'Lorem Ipsum Generator', 'text', 'AlignLeft', 'Generate Lorem Ipsum placeholder text for design mockups, prototypes and templates.', ['lorem ipsum','placeholder text','dummy text','filler text']),
  t(69, 'Case Converter', 'text', 'Type', 'Convert text between UPPERCASE, lowercase, Title Case, Sentence case, aLtErNaTiNg and inverse.', ['case converter','uppercase','lowercase','title case']),
  t(70, 'Word Counter', 'text', 'BookOpen', 'Count words, characters, sentences, paragraphs and reading time in any text.', ['word counter','character counter','word count','reading time']),
  t(71, 'Remove Line Breaks', 'text', 'AlignJustify', 'Remove all line breaks and extra spaces from text to create a single continuous paragraph.', ['remove line breaks','strip newlines','clean text','remove enters']),
  t(72, 'Random Word Generator', 'text', 'Shuffle', 'Generate random words for brainstorming, creative writing, naming and games.', ['random word','word generator','random name','creative writing']),
  t(73, 'Privacy Policy Generator', 'text', 'Shield', 'Generate a complete privacy policy for your website or app in seconds, GDPR-friendly template.', ['privacy policy','privacy policy generator','gdpr policy','website policy']),
  t(74, 'Terms And Conditions Generator', 'text', 'FileText', 'Generate ready-to-use Terms and Conditions for websites, apps and SaaS products.', ['terms and conditions','tos generator','terms of service','legal terms']),
  t(75, 'Disclaimer Generator', 'text', 'AlertTriangle', 'Generate a professional disclaimer for blogs, affiliate sites and businesses.', ['disclaimer generator','legal disclaimer','website disclaimer','blog disclaimer']),
  t(76, 'Text Repeater', 'text', 'Repeat', 'Repeat any text multiple times with a custom separator. Useful for spamming, ASCII art and demos.', ['text repeater','repeat text','duplicate text','copy text']),
  t(77, 'Text Sorter', 'text', 'ArrowDownAZ', 'Sort lines of text alphabetically (A\u2192Z or Z\u2192A) with one click. Clean list organizer.', ['text sorter','sort lines','alphabetical sort','list sorter']),
  t(78, 'Comma Separator', 'text', 'Pilcrow', 'Convert lines into a comma-separated list or vice versa. Perfect for CSV cleanup.', ['comma separator','csv generator','list to csv','comma converter']),
  t(197, 'Number to Word Converter', 'text', 'Type', 'Convert numbers to words in English. Useful for cheques, invoices and legal documents.', ['number to word','number to text','spell number','number in words']),
  t(198, 'Word to Number Converter', 'text', 'Hash', 'Convert written numbers (like \u201ctwo thousand five hundred\u201d) back to digits.', ['word to number','text to number','parse number','convert words']),
  t(201, 'Number to Roman Numerals', 'text', 'Hash', 'Convert any number (1-3999) to Roman numerals (I, V, X, L, C, D, M).', ['number to roman','roman numerals','convert to roman','roman number']),
  t(202, 'Roman Numerals to Number', 'text', 'Hash', 'Convert Roman numerals back to regular numbers. Useful for history, copyright dates and exams.', ['roman to number','roman numerals','convert roman','decode roman']),
  // Domain & Web Tools (100-114)
  t(100, 'Domain to IP', 'web', 'Network', 'Resolve any domain name to its IPv4 and IPv6 addresses. DNS A-record lookup tool.', ['domain to ip','dns lookup','ip resolver','dns a record']),
  t(101, 'Domain Age Checker', 'web', 'Calendar', 'Check the registration age of any domain. Older domains often rank better in SEO.', ['domain age','domain age checker','whois age','seo domain']),
  t(102, 'Whois Domain Lookup', 'web', 'Search', 'Look up Whois information for any domain: registrar, expiry date, name servers and contacts.', ['whois lookup','domain whois','domain info','registrar info']),
  t(103, 'Server Status Checker', 'web', 'Server', 'Check if a website or server is online. Get HTTP response code and latency in milliseconds.', ['server status','uptime checker','server online','website status']),
  t(104, 'Hosting Checker', 'web', 'Server', 'Find the web hosting provider of any website using IP geolocation and ASN data.', ['hosting checker','find hosting','web host lookup','hosting provider']),
  t(105, 'What Is My Browser', 'web', 'Globe', 'Detect your current browser name, version, platform and language with one click.', ['my browser','browser detector','user agent','browser info']),
  t(106, 'What Is My User Agent', 'web', 'Cpu', 'View your full User-Agent string for debugging, testing and browser fingerprinting.', ['user agent','my user agent','ua string','browser fingerprint']),
  t(107, 'DNS Records Checker', 'web', 'Network', 'Look up A, AAAA, MX, NS, TXT, CNAME and other DNS records for any domain.', ['dns records','dns lookup','dns checker','mx records']),
  t(108, 'UUID Generator', 'web', 'Fingerprint', 'Generate v4 UUIDs (universally unique identifiers) for databases, APIs and testing.', ['uuid generator','guid generator','unique id','random uuid']),
  t(109, 'UTM Builder', 'web', 'Link', 'Build trackable UTM URLs for Google Analytics with source, medium, campaign parameters.', ['utm builder','utm generator','campaign url','google analytics']),
  t(110, 'What Is My IP', 'web', 'Wifi', 'Find your public IP address (IPv4 and IPv6) instantly. No setup required.', ['my ip','what is my ip','public ip','ip address']),
  t(111, 'IP Address Lookup', 'web', 'Wifi', 'Look up the geolocation, ISP, country and city of any IPv4 or IPv6 address.', ['ip lookup','ip geolocation','ip locator','ip info']),
  t(112, 'What Is My Screen Resolution', 'web', 'Monitor', 'Detect your current screen resolution, color depth and device pixel ratio.', ['screen resolution','my resolution','display size','pixel ratio']),
  t(113, 'Screen Resolution Simulator', 'web', 'Monitor', 'Simulate various device screen sizes (mobile, tablet, laptop, 4K) to test responsive design.', ['screen simulator','responsive test','device sizes','viewport simulator']),
  t(114, 'WordPress Theme Detector', 'web', 'Layout', 'Detect which WordPress theme and plugins a website is using.', ['wordpress theme detector','find wp theme','what theme','wp detector']),
  // Code Tools (115-127)
  t(115, 'HTML Decode', 'code', 'Code', 'Decode HTML entities (&amp;, &lt;, &gt;, &quot;) back to their original characters.', ['html decode','decode entities','html entities','unescape html']),
  t(116, 'HTML Encode', 'code', 'Code', 'Encode special characters into HTML entities to safely display in browsers.', ['html encode','encode entities','escape html','html escape']),
  t(117, 'URL Decode', 'code', 'Link', 'Decode percent-encoded URLs (%20, %3F) back to readable text.', ['url decode','decode url','percent decode','uri decode']),
  t(118, 'URL Encode', 'code', 'Link', 'Encode URLs and query strings with percent encoding for safe transmission.', ['url encode','encode url','percent encode','uri encode']),
  t(119, 'HTML Beautifier', 'code', 'Code', 'Format and beautify minified HTML with proper indentation and line breaks.', ['html beautifier','format html','prettify html','html formatter']),
  t(120, 'HTML Minifier', 'code', 'Minimize', 'Minify HTML code by removing whitespace and comments. Reduce file size for faster loading.', ['html minifier','minify html','compress html','html optimizer']),
  t(121, 'CSS Beautifier', 'code', 'FileCode', 'Format minified CSS with proper indentation, line breaks and consistent spacing.', ['css beautifier','format css','prettify css','css formatter']),
  t(122, 'CSS Minifier', 'code', 'Minimize', 'Minify CSS to reduce file size and improve page load times.', ['css minifier','minify css','compress css','css optimizer']),
  t(123, 'JavaScript Beautifier', 'code', 'FileCode2', 'Format minified JavaScript with proper indentation and readable structure.', ['javascript beautifier','js formatter','prettify js','format javascript']),
  t(124, 'JavaScript Minifier', 'code', 'Minimize', 'Minify JavaScript code to reduce file size and improve website performance.', ['javascript minifier','minify js','compress javascript','js optimizer']),
  t(125, 'JavaScript DeObfuscator', 'code', 'Eye', 'Deobfuscate and decode obfuscated JavaScript code to read its original logic.', ['js deobfuscator','decode javascript','unobfuscate','reverse js']),
  t(126, 'JavaScript Obfuscator', 'code', 'EyeOff', 'Obfuscate JavaScript code to make it harder to read and reverse engineer.', ['js obfuscator','obfuscate javascript','protect js','encode js']),
  t(127, 'URL Parser', 'code', 'Link', 'Parse a URL into its components: protocol, host, path, query parameters and hash.', ['url parser','parse url','url components','url breakdown']),
  // JSON & Data (99, 128-139)
  t(99, 'JSON to JSON Schema', 'json', 'Braces', 'Generate a JSON Schema (draft-07) from any JSON sample to validate data structures.', ['json schema','generate schema','json validator','schema generator']),
  t(128, 'JSON Viewer', 'json', 'Eye', 'View and explore JSON data in a collapsible tree structure with syntax highlighting.', ['json viewer','view json','json tree','json explorer']),
  t(129, 'JSON Formatter', 'json', 'Braces', 'Format and prettify JSON with proper indentation. Validate syntax in real time.', ['json formatter','prettify json','format json','json beautifier']),
  t(130, 'JSON Validator', 'json', 'CheckCircle', 'Validate JSON syntax and find errors. Get clear error messages with line numbers.', ['json validator','validate json','json syntax','json linter']),
  t(131, 'JSON Editor', 'json', 'Pencil', 'Edit, format and validate JSON in real time with syntax highlighting and error detection.', ['json editor','edit json','json ide','online json editor']),
  t(132, 'JSON Minify', 'json', 'Minimize', 'Minify JSON by removing all whitespace. Reduce API payload sizes.', ['json minify','compress json','minify json','json compressor']),
  t(133, 'XML to JSON', 'json', 'ArrowRightLeft', 'Convert XML documents to JSON format. Perfect for API migrations.', ['xml to json','convert xml','xml converter','xml parser']),
  t(134, 'CSV to JSON', 'json', 'ArrowRightLeft', 'Convert CSV files to JSON arrays. Detect headers automatically.', ['csv to json','convert csv','csv parser','csv converter']),
  t(135, 'TSV to JSON', 'json', 'ArrowRightLeft', 'Convert tab-separated values (TSV) to JSON arrays. Handle Excel-pasted data easily.', ['tsv to json','tsv converter','tab to json','tsv parser']),
  t(136, 'JSON to XML', 'json', 'ArrowRightLeft', 'Convert JSON data to well-formed XML documents with proper structure.', ['json to xml','convert json','xml converter','json to xml']),
  t(137, 'JSON to CSV', 'json', 'ArrowRightLeft', 'Convert JSON arrays to CSV files. Export API data to Excel-friendly format.', ['json to csv','convert json','csv export','json csv']),
  t(138, 'JSON to Text', 'json', 'ArrowRightLeft', 'Flatten JSON into readable key-value text format. Perfect for inspection and logging.', ['json to text','flatten json','json to plain','json export']),
  t(139, 'JSON to TSV', 'json', 'ArrowRightLeft', 'Convert JSON arrays to tab-separated values for spreadsheet imports.', ['json to tsv','convert json','tsv export','tab values']),
  // Image Tools (140-162)
  t(140, 'ICO to PNG', 'image', 'Image', 'Convert ICO favicon files to PNG images with transparency preserved.', ['ico to png','convert ico','favicon converter','ico converter']),
  t(141, 'ICO Converter', 'image', 'Image', 'Convert PNG, JPG or other images to ICO favicon format with multiple sizes.', ['ico converter','png to ico','favicon generator','image to ico']),
  t(142, 'Image to Base64', 'image', 'Image', 'Convert images to Base64-encoded data URIs for embedding in HTML, CSS or JSON.', ['image to base64','base64 image','image encoder','data uri']),
  t(143, 'Base64 to Image', 'image', 'Image', 'Decode Base64 strings back to images and download them as PNG, JPG or WebP.', ['base64 to image','decode base64','base64 decoder','image decoder']),
  t(144, 'Flip Image Online', 'image', 'FlipHorizontal', 'Flip images horizontally or vertically for mirror effects and creative edits.', ['flip image','mirror image','horizontal flip','vertical flip']),
  t(145, 'Rotate Image', 'image', 'RotateCw', 'Rotate images by 90, 180, 270 or any custom degrees with one click.', ['rotate image','image rotation','turn image','rotate photo']),
  t(146, 'Image Enlarger', 'image', 'Maximize', 'Enlarge images up to 4x without losing quality using smart upscaling algorithms.', ['image enlarger','upscale image','enlarge photo','image upscaler']),
  t(147, 'Image Cropper', 'image', 'Crop', 'Crop images to any size or aspect ratio. Perfect for social media and thumbnails.', ['image cropper','crop image','image trimmer','photo cropper']),
  t(148, 'Image Resizer', 'image', 'Maximize', 'Resize images to any dimension in pixels, percentage or preset sizes (HD, 4K, social).', ['image resizer','resize image','photo resizer','image scaler']),
  t(149, 'Image Converter', 'image', 'Image', 'Convert images between JPG, PNG, WebP, BMP, GIF and ICO formats.', ['image converter','convert image','format converter','image formats']),
  t(150, 'JPG to PNG', 'image', 'Image', 'Convert JPG/JPEG images to PNG format with transparency support.', ['jpg to png','jpeg to png','convert jpg','image converter']),
  t(151, 'PNG to JPG', 'image', 'Image', 'Convert PNG images to JPG format with adjustable quality settings.', ['png to jpg','png to jpeg','convert png','image converter']),
  t(152, 'JPG Converter', 'image', 'Image', 'Convert any image format (PNG, WebP, BMP, GIF) to JPG with quality control.', ['jpg converter','convert to jpg','image to jpg','jpeg converter']),
  t(153, 'WebP to JPG', 'image', 'Image', 'Convert WebP images to JPG for universal compatibility with all browsers and apps.', ['webp to jpg','convert webp','webp converter','webp to jpeg']),
  t(154, 'PNG to WebP', 'image', 'Image', 'Convert PNG images to modern WebP format for smaller file sizes and faster loading.', ['png to webp','convert png','webp converter','image optimizer']),
  t(155, 'PNG to BMP', 'image', 'Image', 'Convert PNG images to Windows Bitmap (BMP) format.', ['png to bmp','bmp converter','convert png','bitmap']),
  t(156, 'PNG to GIF', 'image', 'Image', 'Convert PNG images to GIF format for legacy compatibility and simple animations.', ['png to gif','convert png','gif converter','animated gif']),
  t(157, 'PNG to ICO', 'image', 'Image', 'Convert PNG images to ICO favicon format for websites.', ['png to ico','favicon converter','ico generator','website favicon']),
  t(158, 'JPG to WebP', 'image', 'Image', 'Convert JPG images to WebP for smaller file sizes without quality loss.', ['jpg to webp','convert jpg','webp converter','image optimization']),
  t(159, 'JPG to BMP', 'image', 'Image', 'Convert JPG/JPEG images to Bitmap (BMP) format for Windows applications.', ['jpg to bmp','bmp converter','convert jpg','bitmap']),
  t(160, 'JPG to GIF', 'image', 'Image', 'Convert JPG images to GIF format for sharing on legacy platforms.', ['jpg to gif','convert jpg','gif converter','jpeg to gif']),
  t(161, 'JPG to ICO', 'image', 'Image', 'Convert JPG images to ICO favicon format with multi-size support.', ['jpg to ico','favicon generator','ico converter','jpeg to ico']),
  t(162, 'WebP to PNG', 'image', 'Image', 'Convert WebP images to PNG with transparency for editing in design tools.', ['webp to png','convert webp','png converter','webp decoder']),
  // Calculators (163-180, 228)
  t(163, 'Age Calculator', 'calc', 'Cake', 'Calculate your exact age in years, months, days and total lived days from a date of birth.', ['age calculator','calculate age','birthday calculator','years lived']),
  t(164, 'Percentage Calculator', 'calc', 'Percent', 'Calculate percentages, percentage increase/decrease and what percent X is of Y.', ['percentage calculator','calculate percentage','percent calc','percentage of']),
  t(165, 'Average Calculator', 'calc', 'Sigma', 'Calculate the mean, sum, count and average of any list of numbers instantly.', ['average calculator','mean calculator','sum calculator','arithmetic mean']),
  t(166, 'Confidence Interval Calculator', 'calc', 'BarChart3', 'Calculate confidence intervals from sample mean, standard deviation and size at 90/95/99% levels.', ['confidence interval','statistics calculator','ci calculator','margin of error']),
  t(167, 'Sales Tax Calculator', 'calc', 'Receipt', 'Calculate sales tax amounts and totals from price and tax rate. Worldwide tax-rate support.', ['sales tax calculator','vat calculator','tax calc','sales tax']),
  t(168, 'Margin Calculator', 'calc', 'TrendingUp', 'Calculate profit margin, markup and gross profit from cost and revenue.', ['margin calculator','profit margin','markup calculator','gross profit']),
  t(169, 'Probability Calculator', 'calc', 'Dices', 'Calculate the probability of events given favorable outcomes and total outcomes.', ['probability calculator','probability calc','odds calculator','statistics']),
  t(170, 'PayPal Fee Calculator', 'calc', 'DollarSign', 'Calculate PayPal transaction fees (2.9% + $0.49 by default) and your net amount.', ['paypal fee calculator','paypal fees','payment fees','transaction fees']),
  t(171, 'Discount Calculator', 'calc', 'Tag', 'Calculate discount amounts, final prices and total savings from original price and discount percent.', ['discount calculator','sale calculator','discount price','savings']),
  t(172, 'CPM Calculator', 'calc', 'BarChart3', 'Calculate cost per thousand impressions (CPM) from total cost and impression count.', ['cpm calculator','advertising cpm','impression cost','ad metrics']),
  t(173, 'Loan Calculator', 'calc', 'Landmark', 'Calculate monthly loan payments, total interest and total amount paid for any loan.', ['loan calculator','mortgage calculator','monthly payment','interest calculator']),
  t(174, 'GST Calculator', 'calc', 'Receipt', 'Calculate GST/VAT amounts inclusive or exclusive of tax for any country.', ['gst calculator','vat calculator','tax calculator','goods services tax']),
  t(175, 'Days Calculator', 'calc', 'Calendar', 'Calculate the number of days between any two dates. Handles leap years correctly.', ['days calculator','date difference','days between','date calculator']),
  t(176, 'Hours Calculator', 'calc', 'Clock', 'Calculate the duration between two times in hours and minutes. Great for timesheets.', ['hours calculator','time calculator','duration calc','time difference']),
  t(177, 'Month Calculator', 'calc', 'Calendar', 'Calculate the number of months between two dates for subscriptions, contracts and planning.', ['month calculator','months between','date months','duration months']),
  t(178, 'Stripe Fee Calculator', 'calc', 'CreditCard', 'Calculate Stripe transaction fees (2.9% + $0.30) and net amount received.', ['stripe fee calculator','stripe fees','payment processing','transaction fees']),
  t(179, 'Calorie Calculator', 'calc', 'Flame', 'Calculate your Basal Metabolic Rate (BMR) and daily calorie needs based on age and weight.', ['calorie calculator','bmr calculator','calorie needs','daily calories']),
  t(180, 'TDEE Calculator', 'calc', 'Activity', 'Calculate your Total Daily Energy Expenditure (TDEE) based on activity level.', ['tdee calculator','total daily energy','calorie burn','fitness calculator']),
  t(228, 'Adsense Calculator', 'calc', 'DollarSign', 'Estimate Google AdSense earnings from pageviews, CTR and CPC. Project monthly and yearly revenue.', ['adsense calculator','adsense earnings','ad revenue','adsense income']),
  // Unit Converters (181-200)
  t(181, 'Length Converter', 'units', 'Ruler', 'Convert length between meters, feet, inches, kilometers, miles, yards and more.', ['length converter','meters to feet','inches to cm','distance converter']),
  t(182, 'Area Converter', 'units', 'Square', 'Convert area between square meters, square feet, acres, hectares and more.', ['area converter','square meters','acres calculator','land area']),
  t(183, 'Weight Converter', 'units', 'Scale', 'Convert weight between kilograms, pounds, ounces, tons and grams.', ['weight converter','kg to lbs','pounds to kg','mass converter']),
  t(184, 'Volume Converter', 'units', 'FlaskConical', 'Convert volume between liters, gallons, milliliters, cubic meters and cups.', ['volume converter','liters to gallons','ml to oz','liquid converter']),
  t(185, 'Temperature Converter', 'units', 'Thermometer', 'Convert temperature between Celsius, Fahrenheit and Kelvin.', ['temperature converter','celsius to fahrenheit','c to f','temp converter']),
  t(186, 'Time Converter', 'units', 'Clock', 'Convert time between seconds, minutes, hours, days, weeks and years.', ['time converter','seconds to minutes','time units','duration converter']),
  t(187, 'Digital Converter', 'units', 'HardDrive', 'Convert digital storage between bytes, KB, MB, GB, TB and bits.', ['digital converter','byte converter','gb to mb','storage converter']),
  t(188, 'Speed Converter', 'units', 'Gauge', 'Convert speed between km/h, mph, m/s and knots.', ['speed converter','kmh to mph','speed units','velocity converter']),
  t(189, 'Pressure Converter', 'units', 'Gauge', 'Convert pressure between Pa, bar, psi, atm and kPa.', ['pressure converter','psi to bar','pascals','atmospheric pressure']),
  t(190, 'Current Converter', 'units', 'Zap', 'Convert electric current between Amps, milliamps and kiloamps.', ['current converter','amps converter','electric current','milliamps']),
  t(191, 'Voltage Converter', 'units', 'Zap', 'Convert voltage between Volts, millivolts and kilovolts.', ['voltage converter','volts converter','electrical voltage','millivolts']),
  t(192, 'Power Converter', 'units', 'Zap', 'Convert power between Watts, kilowatts, megawatts and horsepower.', ['power converter','watts to hp','kilowatts','power units']),
  t(193, 'Energy Converter', 'units', 'Battery', 'Convert energy between Joules, calories, kWh and BTU.', ['energy converter','joules to calories','kwh converter','energy units']),
  t(194, 'Frequency Converter', 'units', 'Radio', 'Convert frequency between Hz, kHz, MHz and GHz.', ['frequency converter','hertz converter','khz to mhz','wave frequency']),
  t(195, 'Angle Converter', 'units', 'Compass', 'Convert angles between degrees, radians and gradians.', ['angle converter','degrees to radians','angle units','radian converter']),
  t(196, 'Currency Converter', 'units', 'DollarSign', 'Convert between major world currencies with up-to-date exchange rates.', ['currency converter','usd to eur','exchange rates','money converter']),
  t(199, 'Torque Converter', 'units', 'Settings', 'Convert torque between Newton-meters, kilogram-force meters and pound-force feet.', ['torque converter','nm to lb ft','torque units','engineering converter']),
  t(200, 'Charge Converter', 'units', 'Zap', 'Convert electric charge between Coulombs, milliampere-hours and ampere-hours.', ['charge converter','coulombs','mah converter','battery capacity']),
  // Number Systems (203-226)
  t(203, 'Text to Binary', 'numbers', 'Binary', 'Convert text to binary code (8-bit ASCII). Encode messages in 0s and 1s.', ['text to binary','binary encoder','ascii to binary','binary code']),
  t(204, 'Binary to Text', 'numbers', 'Binary', 'Convert binary code back to readable text. Decode 0s and 1s into characters.', ['binary to text','binary decoder','decode binary','binary to ascii']),
  t(205, 'HEX to Binary', 'numbers', 'Binary', 'Convert hexadecimal numbers to binary representation.', ['hex to binary','hexadecimal','binary converter','base conversion']),
  t(206, 'Binary to HEX', 'numbers', 'Binary', 'Convert binary numbers to hexadecimal (base-16) format.', ['binary to hex','hex converter','base conversion','hexadecimal']),
  t(207, 'ASCII to Binary', 'numbers', 'Binary', 'Convert ASCII codes (0-255) to binary representation.', ['ascii to binary','ascii converter','binary encoder','character codes']),
  t(208, 'Binary to ASCII', 'numbers', 'Binary', 'Convert binary numbers back to ASCII character codes.', ['binary to ascii','decode binary','ascii decoder','character codes']),
  t(209, 'Decimal to Binary', 'numbers', 'Binary', 'Convert decimal numbers (base-10) to binary (base-2).', ['decimal to binary','base conversion','number system','binary converter']),
  t(210, 'Binary to Decimal', 'numbers', 'Binary', 'Convert binary numbers (base-2) to decimal (base-10).', ['binary to decimal','base conversion','decode binary','number system']),
  t(211, 'Text to ASCII', 'numbers', 'Binary', 'Convert text characters to their ASCII numeric codes.', ['text to ascii','ascii encoder','character codes','ascii converter']),
  t(212, 'ASCII to Text', 'numbers', 'Binary', 'Convert ASCII numeric codes back to readable text characters.', ['ascii to text','ascii decoder','character codes','decode ascii']),
  t(213, 'HEX to Decimal', 'numbers', 'Binary', 'Convert hexadecimal (base-16) to decimal (base-10) numbers.', ['hex to decimal','hexadecimal','base conversion','number system']),
  t(214, 'Decimal to HEX', 'numbers', 'Binary', 'Convert decimal numbers (base-10) to hexadecimal (base-16).', ['decimal to hex','hex converter','base conversion','hexadecimal']),
  t(215, 'Octal to Binary', 'numbers', 'Binary', 'Convert octal numbers (base-8) to binary (base-2).', ['octal to binary','base conversion','octal converter','number system']),
  t(216, 'Binary to Octal', 'numbers', 'Binary', 'Convert binary (base-2) to octal (base-8) numbers.', ['binary to octal','base conversion','octal converter','number system']),
  t(217, 'Octal to Decimal', 'numbers', 'Binary', 'Convert octal (base-8) numbers to decimal (base-10).', ['octal to decimal','base conversion','octal converter','number system']),
  t(218, 'Decimal to Octal', 'numbers', 'Binary', 'Convert decimal (base-10) to octal (base-8) numbers.', ['decimal to octal','base conversion','octal converter','number system']),
  t(219, 'HEX to Octal', 'numbers', 'Binary', 'Convert hexadecimal (base-16) to octal (base-8) numbers.', ['hex to octal','base conversion','hexadecimal','octal']),
  t(220, 'Octal to HEX', 'numbers', 'Binary', 'Convert octal (base-8) to hexadecimal (base-16) numbers.', ['octal to hex','base conversion','octal converter','hexadecimal']),
  t(221, 'Text to Octal', 'numbers', 'Binary', 'Convert text characters to octal representation.', ['text to octal','octal encoder','character codes','octal converter']),
  t(222, 'Octal to Text', 'numbers', 'Binary', 'Convert octal numbers back to text characters.', ['octal to text','octal decoder','decode octal','character codes']),
  t(223, 'Text to HEX', 'numbers', 'Binary', 'Convert text to hexadecimal representation.', ['text to hex','hex encoder','character codes','hex converter']),
  t(224, 'HEX to Text', 'numbers', 'Binary', 'Convert hexadecimal back to readable text.', ['hex to text','hex decoder','decode hex','character codes']),
  t(225, 'Text to Decimal', 'numbers', 'Binary', 'Convert text characters to decimal character codes.', ['text to decimal','decimal encoder','character codes','decimal converter']),
  t(226, 'Decimal to Text', 'numbers', 'Binary', 'Convert decimal character codes back to readable text.', ['decimal to text','decimal decoder','character codes','decode decimal']),
  // Other Utilities (227, 229-240)
  t(227, 'URL Opener', 'misc', 'ExternalLink', 'Open multiple URLs at once in new browser tabs. Bulk URL opener for productivity.', ['url opener','bulk url opener','open multiple urls','multi url']),
  t(229, 'QR Code Decoder', 'misc', 'QrCode', 'Decode QR codes from images. Upload a QR photo and extract its embedded text or URL.', ['qr code decoder','qr scanner','read qr code','decode qr']),
  t(230, 'QR Code Generator', 'misc', 'QrCode', 'Generate QR codes from any URL, text or contact. Download as PNG with custom sizing.', ['qr code generator','create qr','qr maker','generate qr']),
  t(231, 'Find Facebook ID', 'misc', 'Facebook', 'Find the numeric Facebook ID of any user, page or group from its URL.', ['facebook id finder','find fb id','facebook user id','page id']),
  t(232, 'MD5 Generator', 'misc', 'Hash', 'Generate MD5 hash from any text or string. Useful for checksums and legacy systems.', ['md5 generator','md5 hash','hash generator','md5 encoder']),
  t(233, 'Base64 Decode', 'misc', 'Code', 'Decode Base64 strings back to readable text. UTF-8 safe Base64 decoder.', ['base64 decode','decode base64','base64 decoder','utf-8 decode']),
  t(234, 'Base64 Encode', 'misc', 'Code', 'Encode text or files to Base64 format. Perfect for embedding data in JSON, emails or APIs.', ['base64 encode','encode base64','base64 encoder','data uri']),
  t(235, 'Color Converter', 'misc', 'Palette', 'Convert colors between HEX, RGB, HSL and CSS color names with live preview.', ['color converter','hex to rgb','color picker','color codes']),
  t(236, 'Password Generator', 'misc', 'Key', 'Generate strong, random passwords with customizable length and character sets.', ['password generator','strong password','secure password','random password']),
  t(237, 'VTT to SRT', 'misc', 'Subtitles', 'Convert WebVTT (.vtt) subtitle files to SRT format used by video players.', ['vtt to srt','subtitle converter','vtt converter','convert vtt']),
  t(238, 'SRT to VTT', 'misc', 'Subtitles', 'Convert SRT subtitle files to WebVTT (.vtt) format for HTML5 video.', ['srt to vtt','subtitle converter','srt converter','convert srt']),
  t(239, 'HEX to RGB', 'misc', 'Palette', 'Convert HEX color codes to RGB values. Live color preview included.', ['hex to rgb','color converter','rgb values','hex codes']),
  t(240, 'RGB to HEX', 'misc', 'Palette', 'Convert RGB color values to HEX color codes for CSS and design.', ['rgb to hex','color converter','hex codes','rgb values']),
];

export const getToolBySlug = (slug) => TOOLS.find(x => x.slug === slug);
export const getToolsByCategory = (cat) => TOOLS.filter(x => x.category === cat);
export const POPULAR_SLUGS = ['merge-pdf','word-counter','json-formatter','password-generator','qr-code-generator','case-converter','base64-encode','md5-generator','percentage-calculator','color-converter','image-to-base64','youtube-thumbnail-downloader'];
export const POPULAR_TOOLS = POPULAR_SLUGS.map(s => TOOLS.find(t => t.slug === s)).filter(Boolean);
