import React, { useState, useEffect, useRef } from 'react';
import { Input, Button, Label, Textarea, Icons, CopyBtn } from './_common';

// Base64
export const Base64EncodeTool = () => { const [i,setI]=useState(''); const o=i?btoa(unescape(encodeURIComponent(i))):''; return (<div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div><Label>Text</Label><Textarea value={i} onChange={e=>setI(e.target.value)} className="mt-1.5 min-h-[200px] font-mono text-sm" /></div><div><div className="flex items-center justify-between"><Label>Base64</Label><CopyBtn value={o} /></div><Textarea readOnly value={o} className="mt-1.5 min-h-[200px] font-mono text-sm bg-slate-50" /></div></div>); };
export const Base64DecodeTool = () => { const [i,setI]=useState(''); let o=''; try { o = i ? decodeURIComponent(escape(atob(i))) : ''; } catch(e){ o = 'Invalid base64'; } return (<div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div><Label>Base64</Label><Textarea value={i} onChange={e=>setI(e.target.value)} className="mt-1.5 min-h-[200px] font-mono text-sm" /></div><div><div className="flex items-center justify-between"><Label>Decoded</Label><CopyBtn value={o} /></div><Textarea readOnly value={o} className="mt-1.5 min-h-[200px] font-mono text-sm bg-slate-50" /></div></div>); };

// MD5 (compact implementation)
function md5(str) {
  function rh(n){let j,s='';for(j=0;j<=3;j++)s+=((n>>(j*8+4))&15).toString(16)+((n>>(j*8))&15).toString(16);return s;}
  function ad(x,y){const l=(x&65535)+(y&65535);return(((x>>16)+(y>>16)+(l>>16))<<16)|(l&65535);}
  function rl(n,c){return(n<<c)|(n>>>(32-c));}
  function cm(q,a,b,x,s,t){return ad(rl(ad(ad(a,q),ad(x,t)),s),b);}
  function ff(a,b,c,d,x,s,t){return cm((b&c)|((~b)&d),a,b,x,s,t);}
  function gg(a,b,c,d,x,s,t){return cm((b&d)|(c&(~d)),a,b,x,s,t);}
  function hh(a,b,c,d,x,s,t){return cm(b^c^d,a,b,x,s,t);}
  function ii(a,b,c,d,x,s,t){return cm(c^(b|(~d)),a,b,x,s,t);}
  function cs(s){let n,m=Math.ceil((s.length+8)/64)*16,x=Array(m-1).fill(0);for(n=0;n<s.length;n++)x[n>>2]|=s.charCodeAt(n)<<((n%4)*8);x[n>>2]|=128<<((n%4)*8);x[m-2]=s.length*8;return x;}
  const x=cs(unescape(encodeURIComponent(str))); let a=1732584193,b=-271733879,c=-1732584194,d=271733878;
  for(let i=0;i<x.length;i+=16){const oa=a,ob=b,oc=c,od=d;
    a=ff(a,b,c,d,x[i+0],7,-680876936);d=ff(d,a,b,c,x[i+1],12,-389564586);c=ff(c,d,a,b,x[i+2],17,606105819);b=ff(b,c,d,a,x[i+3],22,-1044525330);
    a=ff(a,b,c,d,x[i+4],7,-176418897);d=ff(d,a,b,c,x[i+5],12,1200080426);c=ff(c,d,a,b,x[i+6],17,-1473231341);b=ff(b,c,d,a,x[i+7],22,-45705983);
    a=ff(a,b,c,d,x[i+8],7,1770035416);d=ff(d,a,b,c,x[i+9],12,-1958414417);c=ff(c,d,a,b,x[i+10],17,-42063);b=ff(b,c,d,a,x[i+11],22,-1990404162);
    a=ff(a,b,c,d,x[i+12],7,1804603682);d=ff(d,a,b,c,x[i+13],12,-40341101);c=ff(c,d,a,b,x[i+14],17,-1502002290);b=ff(b,c,d,a,x[i+15],22,1236535329);
    a=gg(a,b,c,d,x[i+1],5,-165796510);d=gg(d,a,b,c,x[i+6],9,-1069501632);c=gg(c,d,a,b,x[i+11],14,643717713);b=gg(b,c,d,a,x[i+0],20,-373897302);
    a=gg(a,b,c,d,x[i+5],5,-701558691);d=gg(d,a,b,c,x[i+10],9,38016083);c=gg(c,d,a,b,x[i+15],14,-660478335);b=gg(b,c,d,a,x[i+4],20,-405537848);
    a=gg(a,b,c,d,x[i+9],5,568446438);d=gg(d,a,b,c,x[i+14],9,-1019803690);c=gg(c,d,a,b,x[i+3],14,-187363961);b=gg(b,c,d,a,x[i+8],20,1163531501);
    a=gg(a,b,c,d,x[i+13],5,-1444681467);d=gg(d,a,b,c,x[i+2],9,-51403784);c=gg(c,d,a,b,x[i+7],14,1735328473);b=gg(b,c,d,a,x[i+12],20,-1926607734);
    a=hh(a,b,c,d,x[i+5],4,-378558);d=hh(d,a,b,c,x[i+8],11,-2022574463);c=hh(c,d,a,b,x[i+11],16,1839030562);b=hh(b,c,d,a,x[i+14],23,-35309556);
    a=hh(a,b,c,d,x[i+1],4,-1530992060);d=hh(d,a,b,c,x[i+4],11,1272893353);c=hh(c,d,a,b,x[i+7],16,-155497632);b=hh(b,c,d,a,x[i+10],23,-1094730640);
    a=hh(a,b,c,d,x[i+13],4,681279174);d=hh(d,a,b,c,x[i+0],11,-358537222);c=hh(c,d,a,b,x[i+3],16,-722521979);b=hh(b,c,d,a,x[i+6],23,76029189);
    a=hh(a,b,c,d,x[i+9],4,-640364487);d=hh(d,a,b,c,x[i+12],11,-421815835);c=hh(c,d,a,b,x[i+15],16,530742520);b=hh(b,c,d,a,x[i+2],23,-995338651);
    a=ii(a,b,c,d,x[i+0],6,-198630844);d=ii(d,a,b,c,x[i+7],10,1126891415);c=ii(c,d,a,b,x[i+14],15,-1416354905);b=ii(b,c,d,a,x[i+5],21,-57434055);
    a=ii(a,b,c,d,x[i+12],6,1700485571);d=ii(d,a,b,c,x[i+3],10,-1894986606);c=ii(c,d,a,b,x[i+10],15,-1051523);b=ii(b,c,d,a,x[i+1],21,-2054922799);
    a=ii(a,b,c,d,x[i+8],6,1873313359);d=ii(d,a,b,c,x[i+15],10,-30611744);c=ii(c,d,a,b,x[i+6],15,-1560198380);b=ii(b,c,d,a,x[i+13],21,1309151649);
    a=ii(a,b,c,d,x[i+4],6,-145523070);d=ii(d,a,b,c,x[i+11],10,-1120210379);c=ii(c,d,a,b,x[i+2],15,718787259);b=ii(b,c,d,a,x[i+9],21,-343485551);
    a=ad(a,oa);b=ad(b,ob);c=ad(c,oc);d=ad(d,od);
  }
  return rh(a)+rh(b)+rh(c)+rh(d);
}

export const MD5GeneratorTool = () => { const [i, setI] = useState(''); const o = i ? md5(i) : ''; return (<div><Label>Text</Label><Textarea value={i} onChange={e=>setI(e.target.value)} className="mt-1.5 min-h-[140px]" /><div className="mt-4 flex items-center justify-between"><Label>MD5 hash</Label><CopyBtn value={o} /></div><Input readOnly value={o} className="mt-1.5 font-mono bg-slate-50" /></div>); };

// Password generator
export const PasswordGeneratorTool = () => {
  const [len, setLen] = useState(16); const [up, setUp] = useState(true); const [low, setLow] = useState(true); const [num, setNum] = useState(true); const [sym, setSym] = useState(true); const [pwd, setPwd] = useState('');
  const gen = () => { let s=''; if(up) s+='ABCDEFGHIJKLMNOPQRSTUVWXYZ'; if(low) s+='abcdefghijklmnopqrstuvwxyz'; if(num) s+='0123456789'; if(sym) s+='!@#$%^&*()_+-=[]{}|;:,.<>?'; if(!s) return setPwd(''); let p=''; for(let i=0;i<len;i++) p+=s[Math.floor(Math.random()*s.length)]; setPwd(p); };
  useEffect(gen, []);
  const strength = pwd.length>=16 && sym && num ? 'Very strong' : pwd.length>=12 ? 'Strong' : pwd.length>=8 ? 'Medium' : 'Weak';
  return (<div><div className="flex items-center gap-2 p-2 bg-slate-50 border border-slate-200 rounded-lg"><Input readOnly value={pwd} className="border-0 bg-transparent font-mono text-base" /><CopyBtn value={pwd} /><Button size="icon" variant="outline" onClick={gen}><Icons.RefreshCw className="w-4 h-4" /></Button></div><div className="mt-3 text-sm">Strength: <span className="font-semibold text-indigo-700">{strength}</span></div><div className="mt-6 space-y-4"><div><Label>Length: {len}</Label><input type="range" min="4" max="64" value={len} onChange={e=>{setLen(parseInt(e.target.value)); setTimeout(gen,0);}} className="w-full mt-2 accent-indigo-600" /></div><div className="grid grid-cols-2 gap-3">{[['Uppercase',up,setUp],['Lowercase',low,setLow],['Numbers',num,setNum],['Symbols',sym,setSym]].map(([l,v,s])=> <label key={l} className="flex items-center gap-2 text-sm cursor-pointer"><input type="checkbox" checked={v} onChange={e=>{s(e.target.checked); setTimeout(gen,0);}} className="accent-indigo-600" />{l}</label>)}</div><Button onClick={gen} className="bg-indigo-600 hover:bg-indigo-700 text-white">Generate new</Button></div></div>);
};

// UUID
export const UUIDGeneratorTool = () => { const [list, setList] = useState([]); const [count, setCount] = useState(5); const gen = () => { const g = () => 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => { const r = Math.random()*16|0; return (c==='x'?r:(r&0x3|0x8)).toString(16);}); setList(Array(Math.max(1,Math.min(100,parseInt(count)||1))).fill(0).map(g)); }; useEffect(gen, []); return (<div><div className="flex items-center gap-2"><Label>Count</Label><Input type="number" value={count} onChange={e=>setCount(e.target.value)} className="w-24" min="1" max="100" /><Button onClick={gen} className="bg-indigo-600 hover:bg-indigo-700">Generate</Button><CopyBtn value={list.join('\n')} /></div><Textarea readOnly value={list.join('\n')} className="mt-4 min-h-[200px] font-mono text-sm bg-slate-50" /></div>); };

// QR Code
export const QRGeneratorTool = () => { const [text, setText] = useState('https://protooly.app'); const [size, setSize] = useState(300); const url = `https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&data=${encodeURIComponent(text)}`; return (<div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div><Label>Content (text or URL)</Label><Textarea value={text} onChange={e=>setText(e.target.value)} className="mt-1.5 min-h-[140px]" /><div className="mt-3"><Label>Size: {size}px</Label><input type="range" min="100" max="600" value={size} onChange={e=>setSize(parseInt(e.target.value))} className="w-full mt-2 accent-indigo-600" /></div></div><div className="flex flex-col items-center justify-center bg-slate-50 border border-slate-200 rounded-xl p-6">{text && <img src={url} alt="QR" className="max-w-full rounded" />}<a href={url} download className="mt-4 inline-flex items-center gap-1 px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium"><Icons.Download className="w-4 h-4" /> Download</a></div></div>); };

// Color converters
const hexToRgb = (h) => { const m = h.replace('#','').match(/^([\da-f]{3}|[\da-f]{6})$/i); if (!m) return null; let hex = m[1]; if (hex.length===3) hex = hex.split('').map(c=>c+c).join(''); return { r: parseInt(hex.slice(0,2),16), g: parseInt(hex.slice(2,4),16), b: parseInt(hex.slice(4,6),16) }; };
const rgbToHex = (r,g,b) => '#' + [r,g,b].map(x => Math.max(0,Math.min(255,parseInt(x)||0)).toString(16).padStart(2,'0')).join('').toUpperCase();

export const HEXToRGBTool = () => { const [hex, setHex] = useState('#4f46e5'); const rgb = hexToRgb(hex); return (<div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div><Label>HEX</Label><Input value={hex} onChange={e=>setHex(e.target.value)} className="mt-1.5 font-mono" /><Label className="mt-4 block">RGB</Label><Input readOnly value={rgb?`rgb(${rgb.r}, ${rgb.g}, ${rgb.b})`:'Invalid'} className="mt-1.5 font-mono bg-slate-50" /></div><div className="rounded-xl border border-slate-200" style={{background: hex, minHeight: 180}} /></div>); };
export const RGBToHEXTool = () => { const [r,setR]=useState(79); const [g,setG]=useState(70); const [b,setB]=useState(229); const hex = rgbToHex(r,g,b); return (<div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div className="grid grid-cols-3 gap-3"><div><Label>R</Label><Input type="number" value={r} onChange={e=>setR(e.target.value)} className="mt-1.5" /></div><div><Label>G</Label><Input type="number" value={g} onChange={e=>setG(e.target.value)} className="mt-1.5" /></div><div><Label>B</Label><Input type="number" value={b} onChange={e=>setB(e.target.value)} className="mt-1.5" /></div><div className="col-span-3"><Label>HEX</Label><Input readOnly value={hex} className="mt-1.5 font-mono bg-slate-50" /></div></div><div className="rounded-xl border border-slate-200" style={{background: hex, minHeight: 180}} /></div>); };
export const ColorConverterTool = () => { const [hex, setHex] = useState('#4f46e5'); const rgb = hexToRgb(hex); const hsl = (() => { if (!rgb) return ''; let {r,g,b} = rgb; r/=255; g/=255; b/=255; const mx=Math.max(r,g,b),mn=Math.min(r,g,b); let h,s,l=(mx+mn)/2; if (mx===mn){h=s=0;} else {const d=mx-mn; s=l>0.5?d/(2-mx-mn):d/(mx+mn); switch(mx){case r:h=(g-b)/d+(g<b?6:0);break;case g:h=(b-r)/d+2;break;case b:h=(r-g)/d+4;break;} h/=6;} return `hsl(${Math.round(h*360)}, ${Math.round(s*100)}%, ${Math.round(l*100)}%)`;})(); return (<div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div className="space-y-3"><div><Label>HEX</Label><Input value={hex} onChange={e=>setHex(e.target.value)} className="mt-1.5 font-mono" /></div><div><Label>RGB</Label><Input readOnly value={rgb?`rgb(${rgb.r}, ${rgb.g}, ${rgb.b})`:'Invalid'} className="mt-1.5 font-mono bg-slate-50" /></div><div><Label>HSL</Label><Input readOnly value={hsl} className="mt-1.5 font-mono bg-slate-50" /></div></div><div className="rounded-xl border border-slate-200" style={{background: hex, minHeight: 200}} /></div>); };

// Image to base64
export const ImageToBase64Tool = () => { const [data, setData] = useState(''); const handle = (e) => { const f = e.target.files?.[0]; if (!f) return; const r = new FileReader(); r.onload = () => setData(r.result); r.readAsDataURL(f); }; return (<div><label className="block border-2 border-dashed border-slate-300 rounded-xl p-8 text-center cursor-pointer hover:border-indigo-400 hover:bg-indigo-50/40"><input type="file" accept="image/*" onChange={handle} className="hidden" /><Icons.Image className="w-8 h-8 mx-auto text-indigo-500" /><p className="mt-2 text-sm font-medium">Upload an image</p></label>{data && <><div className="mt-4 flex items-center justify-between"><Label>Base64</Label><CopyBtn value={data} /></div><Textarea readOnly value={data} className="mt-1.5 min-h-[160px] font-mono text-xs bg-slate-50" /><img src={data} alt="preview" className="mt-3 max-h-48 rounded border border-slate-200" /></>}</div>); };
export const Base64ToImageTool = () => { const [data, setData] = useState(''); return (<div><Label>Paste Base64 data URI</Label><Textarea value={data} onChange={e=>setData(e.target.value)} className="mt-1.5 min-h-[120px] font-mono text-xs" placeholder="data:image/png;base64,..." />{data && data.startsWith('data:image') && <div className="mt-4"><img src={data} alt="decoded" className="max-h-64 rounded border border-slate-200" /><a href={data} download="image.png" className="mt-3 inline-flex items-center gap-1 px-3 py-2 rounded-lg bg-indigo-600 text-white text-sm"><Icons.Download className="w-4 h-4" /> Download</a></div>}</div>); };

// What is my X
export const WhatIsMyIPTool = () => { const [ip, setIp] = useState('Loading...'); useEffect(() => { fetch('https://api.ipify.org?format=json').then(r=>r.json()).then(d=>setIp(d.ip)).catch(()=>setIp('Unable to fetch')); }, []); return <div className="p-6 rounded-xl bg-indigo-50 border border-indigo-100"><div className="text-xs text-indigo-700 font-semibold uppercase">Your public IP</div><div className="text-3xl font-bold text-slate-900 mt-1 font-mono">{ip}</div></div>; };
export const WhatIsMyBrowserTool = () => { const ua = navigator.userAgent; const br = /Edg/.test(ua)?'Edge':/Chrome/.test(ua)?'Chrome':/Firefox/.test(ua)?'Firefox':/Safari/.test(ua)?'Safari':'Unknown'; return (<div className="space-y-3"><div className="p-4 rounded-lg bg-indigo-50 border border-indigo-100"><div className="text-xs text-indigo-700 font-semibold uppercase">Browser</div><div className="text-2xl font-bold mt-1">{br}</div></div><div className="p-4 rounded-lg bg-slate-50 border border-slate-200"><div className="text-xs text-slate-500 font-semibold uppercase">Platform</div><div className="text-lg mt-1">{navigator.platform}</div></div><div className="p-4 rounded-lg bg-slate-50 border border-slate-200"><div className="text-xs text-slate-500 font-semibold uppercase">Language</div><div className="text-lg mt-1">{navigator.language}</div></div></div>); };
export const WhatIsMyUserAgentTool = () => (<div><Label>User Agent</Label><Textarea readOnly value={navigator.userAgent} className="mt-1.5 font-mono text-sm bg-slate-50" /></div>);
export const WhatIsMyScreenTool = () => (<div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{[['Width',window.screen.width+'px'],['Height',window.screen.height+'px'],['Color depth',window.screen.colorDepth+' bit'],['Pixel ratio',window.devicePixelRatio]].map(([l,v])=> <div key={l} className="p-4 rounded-lg bg-indigo-50 border border-indigo-100"><div className="text-xs text-indigo-700 font-semibold uppercase">{l}</div><div className="text-xl font-bold mt-1">{v}</div></div>)}</div>);
export const ScreenSimulatorTool = () => { const [w, setW] = useState(1280); const [h, setH] = useState(720); const presets = [[375,667,'iPhone'],[768,1024,'iPad'],[1280,720,'Laptop'],[1920,1080,'Desktop']]; return (<div><div className="flex flex-wrap gap-2 mb-3">{presets.map(([pw,ph,n])=> <Button key={n} variant="outline" size="sm" onClick={()=>{setW(pw); setH(ph);}}>{n} ({pw}×{ph})</Button>)}</div><div className="grid grid-cols-2 gap-3 max-w-md"><div><Label>Width</Label><Input type="number" value={w} onChange={e=>setW(parseInt(e.target.value))} className="mt-1.5" /></div><div><Label>Height</Label><Input type="number" value={h} onChange={e=>setH(parseInt(e.target.value))} className="mt-1.5" /></div></div><div className="mt-5 p-4 bg-slate-50 border border-slate-200 rounded-xl overflow-auto"><div className="bg-white border-2 border-indigo-300 rounded shadow-lg flex items-center justify-center text-slate-500 text-sm" style={{width:w/2, height:h/2}}>{w} × {h}</div></div></div>); };

// UTM Builder
export const UTMBuilderTool = () => { const [url, setUrl] = useState('https://example.com'); const [src, setSrc] = useState('newsletter'); const [med, setMed] = useState('email'); const [cmp, setCmp] = useState('spring-sale'); const [trm, setTrm] = useState(''); const [cnt, setCnt] = useState(''); const params = new URLSearchParams(); if(src) params.set('utm_source',src); if(med) params.set('utm_medium',med); if(cmp) params.set('utm_campaign',cmp); if(trm) params.set('utm_term',trm); if(cnt) params.set('utm_content',cnt); const out = url+(url.includes('?')?'&':'?')+params.toString(); return (<div className="space-y-3"><div><Label>Website URL</Label><Input value={url} onChange={e=>setUrl(e.target.value)} className="mt-1.5" /></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><div><Label>Source</Label><Input value={src} onChange={e=>setSrc(e.target.value)} className="mt-1.5" /></div><div><Label>Medium</Label><Input value={med} onChange={e=>setMed(e.target.value)} className="mt-1.5" /></div><div><Label>Campaign</Label><Input value={cmp} onChange={e=>setCmp(e.target.value)} className="mt-1.5" /></div><div><Label>Term</Label><Input value={trm} onChange={e=>setTrm(e.target.value)} className="mt-1.5" /></div><div><Label>Content</Label><Input value={cnt} onChange={e=>setCnt(e.target.value)} className="mt-1.5" /></div></div><div><div className="flex items-center justify-between"><Label>Tagged URL</Label><CopyBtn value={out} /></div><Textarea readOnly value={out} className="mt-1.5 font-mono text-sm bg-slate-50" /></div></div>); };

export const URLOpenerTool = () => { const [urls, setUrls] = useState(''); const open = () => urls.split(/\s+/).filter(Boolean).forEach(u => window.open(u, '_blank')); return (<div><Label>URLs (one per line)</Label><Textarea value={urls} onChange={e=>setUrls(e.target.value)} className="mt-1.5 min-h-[160px] font-mono text-sm" placeholder="https://example.com" /><Button onClick={open} className="mt-3 bg-indigo-600 hover:bg-indigo-700">Open all in new tabs</Button></div>); };

export const KeywordDensityTool = () => { const [t, setT] = useState(''); const words = (t.toLowerCase().match(/[a-z؀-ۿ]+/g) || []); const total = words.length; const map = {}; words.forEach(w => { if (w.length<3) return; map[w] = (map[w]||0) + 1; }); const list = Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,20); return (<div><Textarea value={t} onChange={e=>setT(e.target.value)} placeholder="Paste content..." className="min-h-[180px]" /><div className="mt-4 text-sm text-slate-600">Total words: <b>{total}</b></div>{list.length>0 && <table className="mt-3 w-full text-sm"><thead><tr className="text-left text-xs text-slate-500"><th className="py-2">Keyword</th><th>Count</th><th>Density</th></tr></thead><tbody>{list.map(([w,c]) => <tr key={w} className="border-t border-slate-100"><td className="py-2 font-medium">{w}</td><td>{c}</td><td>{(c/total*100).toFixed(2)}%</td></tr>)}</tbody></table>}</div>); };

// Meta Tag generator
export const MetaTagTool = () => { const [t, setT] = useState('My Page'); const [d, setD] = useState('Page description'); const [k, setK] = useState('keyword1, keyword2'); const out = `<title>${t}</title>\n<meta name="description" content="${d}">\n<meta name="keywords" content="${k}">\n<meta property="og:title" content="${t}">\n<meta property="og:description" content="${d}">\n<meta name="twitter:card" content="summary_large_image">`; return (<div className="space-y-3"><div><Label>Title</Label><Input value={t} onChange={e=>setT(e.target.value)} className="mt-1.5" /></div><div><Label>Description</Label><Textarea value={d} onChange={e=>setD(e.target.value)} className="mt-1.5" /></div><div><Label>Keywords</Label><Input value={k} onChange={e=>setK(e.target.value)} className="mt-1.5" /></div><div className="flex items-center justify-between"><Label>Tags</Label><CopyBtn value={out} /></div><Textarea readOnly value={out} className="min-h-[180px] font-mono text-sm bg-slate-50" /></div>); };
export const OGGeneratorTool = MetaTagTool;
export const RobotsTool = () => { const [allow, setAllow] = useState(true); const [sitemap, setSitemap] = useState('https://example.com/sitemap.xml'); const out = `User-agent: *\n${allow?'Allow: /':'Disallow: /'}\nSitemap: ${sitemap}`; return (<div className="space-y-3"><label className="flex items-center gap-2"><input type="checkbox" checked={allow} onChange={e=>setAllow(e.target.checked)} className="accent-indigo-600" /> Allow all crawlers</label><div><Label>Sitemap URL</Label><Input value={sitemap} onChange={e=>setSitemap(e.target.value)} className="mt-1.5" /></div><div className="flex items-center justify-between"><Label>robots.txt</Label><CopyBtn value={out} /></div><Textarea readOnly value={out} className="font-mono text-sm bg-slate-50 min-h-[120px]" /></div>); };
export const HtaccessTool = () => { const [from, setFrom] = useState('/old-page'); const [to, setTo] = useState('https://example.com/new-page'); const out = `Redirect 301 ${from} ${to}`; return (<div className="space-y-3"><div><Label>From path</Label><Input value={from} onChange={e=>setFrom(e.target.value)} className="mt-1.5" /></div><div><Label>To URL</Label><Input value={to} onChange={e=>setTo(e.target.value)} className="mt-1.5" /></div><div className="flex items-center justify-between"><Label>Rule</Label><CopyBtn value={out} /></div><Input readOnly value={out} className="font-mono bg-slate-50" /></div>); };
export const FAQSchemaTool = () => { const [q, setQ] = useState('What is Protooly?'); const [a, setA] = useState('Protooly is an all-in-one toolkit.'); const out = JSON.stringify({ '@context':'https://schema.org','@type':'FAQPage', mainEntity:[{ '@type':'Question', name:q, acceptedAnswer:{'@type':'Answer', text:a}}]}, null, 2); return (<div className="space-y-3"><div><Label>Question</Label><Input value={q} onChange={e=>setQ(e.target.value)} className="mt-1.5" /></div><div><Label>Answer</Label><Textarea value={a} onChange={e=>setA(e.target.value)} className="mt-1.5" /></div><div className="flex items-center justify-between"><Label>JSON-LD</Label><CopyBtn value={out} /></div><Textarea readOnly value={out} className="font-mono text-sm bg-slate-50 min-h-[180px]" /></div>); };

export const YTEmbedTool = () => { const [url, setUrl] = useState('https://www.youtube.com/watch?v=dQw4w9WgXcQ'); const id = (url.match(/(?:v=|youtu\.be\/)([\w-]+)/) || [])[1] || ''; const out = id ? `<iframe width="560" height="315" src="https://www.youtube.com/embed/${id}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>` : ''; return (<div className="space-y-3"><div><Label>YouTube URL</Label><Input value={url} onChange={e=>setUrl(e.target.value)} className="mt-1.5" /></div><div className="flex items-center justify-between"><Label>Embed code</Label><CopyBtn value={out} /></div><Textarea readOnly value={out} className="font-mono text-sm bg-slate-50 min-h-[120px]" />{id && <div className="mt-3" dangerouslySetInnerHTML={{__html: out}} />}</div>); };

export const YTMoneyTool = () => { const [views, setViews] = useState(100000); const lo = (views*0.001).toFixed(2); const hi = (views*0.005).toFixed(2); return (<div className="max-w-md"><Label>Monthly views</Label><Input type="number" value={views} onChange={e=>setViews(e.target.value)} className="mt-1.5" /><div className="mt-4 p-5 rounded-xl bg-indigo-50 border border-indigo-100"><div className="text-xs font-semibold text-indigo-700 uppercase">Estimated monthly earnings</div><div className="text-3xl font-bold mt-1">${lo} — ${hi}</div></div></div>); };

export const PrivacyGenTool = () => { const [site, setSite] = useState('Protooly'); const [email, setEmail] = useState('hello@example.com'); const out = `Privacy Policy for ${site}\n\nLast updated: ${new Date().toLocaleDateString()}\n\n${site} respects your privacy. We collect minimal information to operate our services. We do not sell personal information.\n\nContact: ${email}`; return (<div className="space-y-3"><div className="grid grid-cols-2 gap-3"><div><Label>Site name</Label><Input value={site} onChange={e=>setSite(e.target.value)} className="mt-1.5" /></div><div><Label>Contact email</Label><Input value={email} onChange={e=>setEmail(e.target.value)} className="mt-1.5" /></div></div><div className="flex items-center justify-between"><Label>Privacy Policy</Label><CopyBtn value={out} /></div><Textarea readOnly value={out} className="min-h-[220px] bg-slate-50" /></div>); };
export const TermsGenTool = PrivacyGenTool;
export const DisclaimerGenTool = PrivacyGenTool;

export const VTTtoSRTTool = () => { const [i, setI] = useState(''); const o = i.replace(/^WEBVTT.*$/m,'').replace(/(\d{2}:\d{2}:\d{2})\.(\d{3})/g,'$1,$2').trim().split(/\n\n+/).map((b,i)=>`${i+1}\n${b}`).join('\n\n'); return (<div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div><Label>VTT</Label><Textarea value={i} onChange={e=>setI(e.target.value)} className="mt-1.5 min-h-[220px] font-mono text-sm" /></div><div><div className="flex items-center justify-between"><Label>SRT</Label><CopyBtn value={o} /></div><Textarea readOnly value={o} className="mt-1.5 min-h-[220px] font-mono text-sm bg-slate-50" /></div></div>); };
export const SRTtoVTTTool = () => { const [i, setI] = useState(''); const o = 'WEBVTT\n\n' + i.replace(/^\d+\s*\n/gm,'').replace(/(\d{2}:\d{2}:\d{2}),(\d{3})/g,'$1.$2'); return (<div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div><Label>SRT</Label><Textarea value={i} onChange={e=>setI(e.target.value)} className="mt-1.5 min-h-[220px] font-mono text-sm" /></div><div><div className="flex items-center justify-between"><Label>VTT</Label><CopyBtn value={o} /></div><Textarea readOnly value={o} className="mt-1.5 min-h-[220px] font-mono text-sm bg-slate-50" /></div></div>); };
