import * as Text from './textTools';
import * as Data from './dataTools';
import * as Calc from './calculatorTools';
import * as Units from './unitTools';
import * as Misc from './miscTools';
import * as Net from './netTools';
import * as Img from './imageTools';
import * as PDF from './pdfTools';
import * as AI from './aiTools';
import * as YT from './youtubeTools';
import * as Extra from './extraTools';
import React from 'react';

export const toolRegistry = {
  // Text
  'word-counter': Text.WordCounterTool,
  'case-converter': Text.CaseConverterTool,
  'backwards-text-generator': Text.ReverseTextTool,
  'text-to-slug': Text.TextToSlugTool,
  'remove-line-breaks': Text.RemoveLineBreaksTool,
  'text-repeater': Text.TextRepeaterTool,
  'text-sorter': Text.TextSorterTool,
  'comma-separator': Text.CommaSeparatorTool,
  'text-to-hashtags': Text.TextToHashtagsTool,
  'text-compare-online': Text.TextCompareTool,
  'lorem-ipsum-generator': Text.LoremIpsumTool,
  'random-word-generator': Text.RandomWordTool,
  'number-to-roman-numerals': Text.NumberToRomanTool,
  'roman-numerals-to-number': Text.RomanToNumberTool,
  'number-to-word-converter': Text.NumberToWordTool,
  'word-to-number-converter': Text.WordToNumberTool,
  // JSON & Data
  'json-formatter': Data.JSONFormatterTool,
  'json-viewer': Data.JSONViewerTool,
  'json-editor': Data.JSONEditorTool,
  'json-minify': Data.JSONMinifyTool,
  'json-validator': Data.JSONValidatorTool,
  'json-to-csv': Data.JSONToCSVTool,
  'csv-to-json': Data.CSVToJSONTool,
  'json-to-xml': Data.JSONToXMLTool,
  'xml-to-json': Data.XMLToJSONTool,
  'tsv-to-json': Data.TSVToJSONTool,
  'json-to-tsv': Data.JSONToTSVTool,
  'json-to-text': Data.JSONToTextTool,
  'json-to-json-schema': Data.JSONToSchemaTool,
  // Code
  'html-encode': Data.HTMLEncodeTool,
  'html-decode': Data.HTMLDecodeTool,
  'url-encode': Data.URLEncodeTool,
  'url-decode': Data.URLDecodeTool,
  'html-beautifier': Data.HTMLBeautifyTool,
  'html-minifier': Data.HTMLMinifyTool,
  'css-beautifier': Data.CSSBeautifyTool,
  'css-minifier': Data.CSSMinifyTool,
  'javascript-beautifier': Data.JSBeautifyTool,
  'javascript-minifier': Data.JSMinifyTool,
  'javascript-obfuscator': Data.JSObfuscateTool,
  'javascript-deobfuscator': Data.JSDeObfuscateTool,
  'url-parser': Data.URLParserTool,
  // Calculators
  'age-calculator': Calc.AgeCalculatorTool,
  'percentage-calculator': Calc.PercentageCalculatorTool,
  'average-calculator': Calc.AverageCalculatorTool,
  'discount-calculator': Calc.DiscountCalculatorTool,
  'sales-tax-calculator': Calc.SalesTaxCalculatorTool,
  'margin-calculator': Calc.MarginCalculatorTool,
  'loan-calculator': Calc.LoanCalculatorTool,
  'gst-calculator': Calc.GSTCalculatorTool,
  'paypal-fee-calculator': Calc.PayPalFeeTool,
  'stripe-fee-calculator': Calc.StripeFeeTool,
  'cpm-calculator': Calc.CPMCalculatorTool,
  'days-calculator': Calc.DaysCalculatorTool,
  'hours-calculator': Calc.HoursCalculatorTool,
  'month-calculator': Calc.MonthCalculatorTool,
  'confidence-interval-calculator': Calc.ConfidenceIntervalTool,
  'probability-calculator': Calc.ProbabilityTool,
  'calorie-calculator': Calc.CalorieCalculatorTool,
  'tdee-calculator': Calc.TDEECalculatorTool,
  'adsense-calculator': Calc.AdsenseCalculatorTool,
  // Unit converters
  'length-converter': Units.LengthConverter,
  'weight-converter': Units.WeightConverter,
  'area-converter': Units.AreaConverter,
  'volume-converter': Units.VolumeConverter,
  'temperature-converter': Units.TemperatureConverter,
  'time-converter': Units.TimeConverter,
  'digital-converter': Units.DigitalConverter,
  'speed-converter': Units.SpeedConverter,
  'pressure-converter': Units.PressureConverter,
  'current-converter': Units.CurrentConverter,
  'voltage-converter': Units.VoltageConverter,
  'power-converter': Units.PowerConverter,
  'energy-converter': Units.EnergyConverter,
  'frequency-converter': Units.FrequencyConverter,
  'angle-converter': Units.AngleConverter,
  'torque-converter': Units.TorqueConverter,
  'charge-converter': Units.ChargeConverter,
  'currency-converter': Units.CurrencyConverter,
  // Number systems
  'text-to-binary': Units.TextToBinary,
  'binary-to-text': Units.BinaryToText,
  'text-to-hex': Units.TextToHex,
  'hex-to-text': Units.HexToText,
  'text-to-octal': Units.TextToOctal,
  'octal-to-text': Units.OctalToText,
  'text-to-decimal': Units.TextToDecimal,
  'decimal-to-text': Units.DecimalToText,
  'text-to-ascii': Units.TextToASCII,
  'ascii-to-text': Units.ASCIIToText,
  'ascii-to-binary': Units.ASCIIToBinary,
  'binary-to-ascii': Units.BinaryToASCII,
  'decimal-to-binary': Units.DecimalToBinary,
  'binary-to-decimal': Units.BinaryToDecimal,
  'hex-to-decimal': Units.HexToDecimal,
  'decimal-to-hex': Units.DecimalToHex,
  'octal-to-decimal': Units.OctalToDecimal,
  'decimal-to-octal': Units.DecimalToOctal,
  'hex-to-binary': Units.HexToBinary,
  'binary-to-hex': Units.BinaryToHex,
  'octal-to-binary': Units.OctalToBinary,
  'binary-to-octal': Units.BinaryToOctal,
  'hex-to-octal': Units.HexToOctal,
  'octal-to-hex': Units.OctalToHex,
  // Misc & utilities
  'base64-encode': Misc.Base64EncodeTool,
  'base64-decode': Misc.Base64DecodeTool,
  'md5-generator': Misc.MD5GeneratorTool,
  'password-generator': Misc.PasswordGeneratorTool,
  'uuid-generator': Misc.UUIDGeneratorTool,
  'qr-code-generator': Misc.QRGeneratorTool,
  'hex-to-rgb': Misc.HEXToRGBTool,
  'rgb-to-hex': Misc.RGBToHEXTool,
  'color-converter': Misc.ColorConverterTool,
  'image-to-base64': Misc.ImageToBase64Tool,
  'base64-to-image': Misc.Base64ToImageTool,
  'what-is-my-ip': Misc.WhatIsMyIPTool,
  'what-is-my-browser': Misc.WhatIsMyBrowserTool,
  'what-is-my-user-agent': Misc.WhatIsMyUserAgentTool,
  'what-is-my-screen-resolution': Misc.WhatIsMyScreenTool,
  'screen-resolution-simulator': Misc.ScreenSimulatorTool,
  'utm-builder': Misc.UTMBuilderTool,
  'url-opener': Misc.URLOpenerTool,
  'keyword-density-checker': Misc.KeywordDensityTool,
  'meta-tag-generator': Misc.MetaTagTool,
  'open-graph-generator': Misc.OGGeneratorTool,
  'robots-txt-generator': Misc.RobotsTool,
  'htaccess-redirect-generator': Misc.HtaccessTool,
  'faq-schema-generator': Misc.FAQSchemaTool,
  'youtube-embed-code-generator': Misc.YTEmbedTool,
  'youtube-money-calculator': Misc.YTMoneyTool,
  'privacy-policy-generator': Misc.PrivacyGenTool,
  'terms-and-conditions-generator': Misc.TermsGenTool,
  'disclaimer-generator': Misc.DisclaimerGenTool,
  'vtt-to-srt': Misc.VTTtoSRTTool,
  'srt-to-vtt': Misc.SRTtoVTTTool,
  // Network (server-backed)
  'http-status-code-checker': Net.HTTPStatusTool,
  'get-http-headers': Net.GetHeadersTool,
  'page-size-checker': Net.PageSizeTool,
  'domain-to-ip': Net.DomainToIPTool,
  'dns-records-checker': Net.DNSRecordsTool,
  'server-status-checker': Net.ServerStatusTool,
  'redirect-checker': Net.RedirectChainTool,
  // Image (canvas)
  'jpg-to-png': Img.JPGToPNG,
  'png-to-jpg': Img.PNGToJPG,
  'jpg-converter': Img.JPGConverter,
  'webp-to-jpg': Img.WebPToJPG,
  'png-to-webp': Img.PNGToWebP,
  'png-to-bmp': Img.PNGToBMP,
  'png-to-gif': Img.PNGToGIF,
  'jpg-to-webp': Img.JPGToWebP,
  'jpg-to-bmp': Img.JPGToBMP,
  'jpg-to-gif': Img.JPGToGIF,
  'webp-to-png': Img.WebPToPNG,
  'png-to-ico': Img.PNGToICO,
  'jpg-to-ico': Img.JPGToICO,
  'ico-converter': Img.ICOConverter,
  'ico-to-png': Img.ICOToPNG,
  'image-resizer': Img.ImageResizer,
  'image-enlarger': Img.ImageEnlarger,
  'rotate-image': Img.ImageRotate,
  'flip-image-online': Img.ImageFlip,
  'image-cropper': Img.ImageCropper,
  'image-converter': Img.ImageConverterTool,
  // PDF
  'merge-pdf': PDF.MergePDF,
  'split-pdf': PDF.SplitPDF,
  'rotate-pdf': PDF.RotatePDF,
  'watermark-pdf': PDF.WatermarkPDF,
  'pdf-page-numbers': PDF.PageNumbersPDF,
  'jpg-to-pdf': PDF.JPGtoPDF,
  'pdf-to-jpg': PDF.PDFtoJPG,
  'protect-pdf': PDF.ProtectPDF,
  'organize-pdf': PDF.OrganizePDF,
  'compress-pdf': PDF.CompressPDF,
  // AI Tools
  'ai-summarizer': AI.AISummarizer,
  'paraphrasing-tool': AI.AIParaphrase,
  'translate-text': AI.AITranslate,
  'ai-text-generator': AI.AIGenerate,
  'ai-grammar-checker': AI.AIGrammar,
  'ai-humanizer': AI.AIHumanizer,
  'article-rewriter': AI.AIRewriter,
  'citation-generator': AI.AICitation,
  'ai-detector': AI.AIDetector,
  'reverse-image-search': AI.ReverseImageSearch,
  'plagiarism-checker': AI.PlagiarismChecker,
  // YouTube
  'youtube-thumbnail-downloader': YT.YTThumbnailDownloader,
  'youtube-title-extractor': YT.YTTitleExtractor,
  'youtube-description-extractor': YT.YTDescriptionExtractor,
  'youtube-channel-logo-downloader': YT.YTChannelLogoDownloader,
  'youtube-channel-banner-downloader': YT.YTBannerDownloader,
  'youtube-channel-id-finder': YT.YTChannelIDFinder,
  'youtube-region-restriction-checker': YT.YTRegionRestriction,
  'youtube-video-statistics': YT.YTVideoStatistics,
  'youtube-channel-statistics': YT.YTChannelStatistics,
  'youtube-channel-finder': YT.YTChannelFinder,
  'youtube-tag-generator': YT.YTTagGenerator,
  'youtube-hashtag-generator': YT.YTHashtagGenerator,
  'youtube-tag-extractor': YT.YTTagExtractor,
  'youtube-hashtag-extractor': YT.YTHashtagExtractor,
  'youtube-title-generator': YT.YTTitleGenerator,
  'youtube-description-generator': YT.YTDescriptionGenerator,
  'youtube-trends-checker': YT.YTTrendsChecker,
  // Extra tools
  'qr-code-decoder': Extra.QRDecoder,
  'find-facebook-id': Extra.FacebookID,
  'ip-address-lookup': Extra.IPLookup,
  'whois-domain-lookup': Extra.WhoisLookup,
  'domain-age-checker': Extra.DomainAge,
  'hosting-checker': Extra.HostingChecker,
  'backlink-checker': Extra.BacklinkChecker,
  'domain-authority-checker': Extra.DAChecker,
  'page-authority-checker': Extra.PAChecker,
  'da-pa-checker': Extra.DAPAChecker,
  'moz-rank-checker': Extra.MozRank,
  'google-index-checker': Extra.GoogleIndex,
  'google-cache-checker': Extra.GoogleCache,
  'seo-site-audit': Extra.SEOAudit,
  'wordpress-theme-detector': Extra.WPThemeDetector,
  'keywords-suggestion-tool': Extra.KeywordSuggestion,
  'meta-tags-analyzer': Extra.MetaTagAnalyzer,
  'open-graph-checker': Extra.OpenGraphChecker,
  'url-rewriting-tool': Extra.URLRewriter,
  'referring-domains-checker': Extra.ReferringDomains,
  'broken-backlink-checker': Extra.BrokenBacklinkChecker,
  'lost-backlinks-checker': Extra.LostBacklinks,
  'new-backlinks-checker': Extra.NewBacklinks,
  'anchor-text-checker': Extra.AnchorTextChecker,
  'competitor-backlink-checker': Extra.CompetitorBacklinks,
  'backlink-gap-tool': Extra.BacklinkGap,
  'link-building-opportunity-finder': Extra.LinkBuildingFinder,
  'toxic-backlink-checker': Extra.ToxicBacklinks,
  'scan-to-pdf': Extra.ScanToPDF,
  'ocr-pdf': Extra.OCRPDF,
  'compare-pdf': Extra.ComparePDF,
  'sign-pdf': Extra.SignPDF,
  'edit-pdf': Extra.EditPDF,
  'pdf-forms': Extra.PDFForms,
  'crop-pdf': Extra.CropPDF,
  'redact-pdf': Extra.RedactPDF,
  'unlock-pdf': Extra.UnlockPDF,
  'repair-pdf': Extra.RepairPDF,
  'pdf-to-pdf-a': Extra.PDFtoA,
  'html-to-pdf': Extra.HTMLtoPDF,
  // Office docs (informational)
  'word-to-pdf': () => <Extra.OfficetoPDF accept=".docx,.doc" />,
  'powerpoint-to-pdf': () => <Extra.OfficetoPDF accept=".pptx,.ppt" />,
  'excel-to-pdf': () => <Extra.OfficetoPDF accept=".xlsx,.xls" />,
  'pdf-to-word': () => <Extra.PDFtoOffice ext="docx" />,
  'pdf-to-powerpoint': () => <Extra.PDFtoOffice ext="pptx" />,
  'pdf-to-excel': () => <Extra.PDFtoOffice ext="xlsx" />,
};
